### ISSUE TITLE
how can add buttons to notification?

### ISSUE THREAD

**Issue by RamiHI** [gdelataillade/alarm#1]
how can add buttons to notification?

**Comment by gdelataillade** [comment]
This feature is not available yet. I'm planning to develop it in the next weeks, or sooner if you need. Feel free to contribute to the package if you want, using this documentation: https://pub.dev/packages/flutter_local_notifications#notification-actions

**Comment by RamiHI** [comment]
Does an alarm notification arrive in the background?

**Comment by RamiHI** [comment]
I have made some modifications and I am trying to upload the code but it does not allow me

**Comment by gdelataillade** [comment]
As explained in the [README.md](https://pub.dev/packages/alarm#feature-request), in order to contribute you have to fork the repository and submit a pull request.

**Comment by RamiHI** [comment]
I pull request

**Comment by gdelataillade** [comment]
Thank you for your contribution !
I'm very busy at the moment so give me a few days to review your PR. In the meantime, you can use your fork instead of my alarm package as a dependency in your project.

**Comment by RamiHI** [comment]
Thank you, but how can I make the alarm ring even if the application is destroyed?

**Comment by gdelataillade** [comment]
In iOS, if the app is killed, there is no way the alarm could ring...
However, I'm planning to add a feature that would send a notification like "_The app has been killed. Please open the app or the alarm will not ring_" at the moment the user kills the app. This way, the user will be aware the alarm will not ring if he doesn't re-open the app.

**Comment by gdelataillade** [comment]
Here's an example of the app Alarmy that shows this kind of notification when the iOS app is killed:
![image](https://user-images.githubusercontent.com/32983806/211571529-e5a17755-e527-4db8-8479-9a117b560801.png)

**Comment by RamiHI** [comment]
I think if a schedule notification is sent it would be better

**Comment by gdelataillade** [comment]
Can you elaborate ? I'm not sure to understand.

**Comment by RamiHI** [comment]
I mean that the schedule notification is sent instead of the normal notification because the scheduled notification will appear even if the application is destroyed

**Comment by gdelataillade** [comment]
In iOS, when a user sets an alarm, a notification is scheduled. If the app is killed, the notification will still show, but the audio of the alarm will not be played. That's why I would like to show a notification to warn the user at the moment he kills the app.
Let me know if it's not the answer you were expecting.

**Comment by gdelataillade** [comment]
You are right...
I didn't notice before but on Android too if you kill the app, the alarm will never ring.
I don't have a solution for this at the moment. However, the feature that I was talking about earlier that shows a notification when the user kills the app is being developed.
Furthermore, a workaround that the app Alarmy uses is that in the case the user kills the app, when the alarm is supposed to ring, we show multiple notifications with sound that could replace the alarm sound.

**Comment by moosalim** [comment]
> You are right... I didn't notice before but on Android too if you kill the app, the alarm will never ring. I don't have a solution for this at the moment. However, the feature that I was talking about earlier that shows a notification when the user kills the app is being developed. Furthermore, a workaround that the app Alarmy uses is that in the case the user kills the app, when the alarm is supposed to ring, we show multiple notifications with sound that could replace the alarm sound.

There is a good solution for Android see this : https://stackoverflow.com/questions/65475678/how-to-launch-app-like-googles-alarm-app-using-alarm-manager-in-flutter

I have tested it and it works fine, you just need to fork Android Alarm_manager_plugin and make these changes

**Comment by gdelataillade** [comment]
Since version `3.0.0`, alarms can ring even if app was terminated.
