### ISSUE TITLE
The alarm does not sound

### ISSUE THREAD

**Issue by ilhamfadilah05** [gdelataillade/alarm#101]
**Alarm plugin version**
Alarm v2.1.0

The alarm does not sound when it is in the background or foreground. I've added the AudioPath asset. Please help. Thanks

**Device info**
iOS : Iphone X (iOS v16.7)
Android : android 8 and android 13

**Comment by gdelataillade** [comment]
Hi @ilhamfadilah05 

Do you see any error log in your debug console ? That would help me identify your issue.

**Comment by ilhamfadilah05** [comment]
Hi @gdelataillade 

To debug the console there are no errors. but the notification sound is silent.
Tomorrow I will make a video for this bug

**Comment by ilhamfadilah05** [comment]
Hi @gdelataillade

is there a solution?

**Comment by gdelataillade** [comment]
Hi @ilhamfadilah05

As explained in the README, if you kill the app then the alarm can't ring. Only the notification will display.

However, I'm currently working on your issue. I'm trying to make android alarms ring even if app was killed. I'll keep you updated.
