### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'bool' in type cast

### ISSUE THREAD

**Issue by msh-nayan** [gdelataillade/alarm#103]
**Alarm plugin version**
*alarm: ^2.1.0*

**Describe the bug**
*Unhandled Exception: type 'Null' is not a subtype of type 'bool' in type cast*

**To Reproduce**
*Steps to reproduce the behavior:*
1. *Form an alarm settings*
```
AlarmSettings tourAlarmSettings(int id, DateTime dateTime) {
    final alarmSettings = AlarmSettings(
        id: id,
        dateTime: dateTime,
        assetAudioPath: 'assets/alarm_tune.mp3',
        loopAudio: false,
        vibrate: true,
        volumeMax: false,
        fadeDuration: 0,
        notificationTitle: '',
        notificationBody: '',
        enableNotificationOnKill: false,
        stopOnNotificationOpen: true);
    return alarmSettings;
  }
```
2. *Set an alarm*
```
void setAlarm(AlarmSettings alarmSettings) {
    Alarm.set(alarmSettings: alarmSettings).then((value) {
      int id = alarmSettings.id;
      debugPrint('$tag >> set_alarm >> id >> $id >> alarm_settings >> ${alarmSettings.toString()}');
    });
  }
```

**Expected behavior**
*Alarm should be saved on given date time.*

**Screenshots**
<img width="941" alt="Screenshot 2023-10-23 at 4 56 21 PM" src="https://github.com/gdelataillade/alarm/assets/2936631/fe954615-e41a-43b4-8c81-72fbe7f72d2a">
*Getting the following error while creating alarm*
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'bool' in type cast
#0      new AlarmSettings.fromJson (package:alarm/model/alarm_settings.dart:106:66)
#1      AlarmStorage.getSavedAlarms (package:alarm/service/storage.dart:49:34)
#2      Alarm.getAlarms (package:alarm/alarm.dart:172:58)
#3      Alarm.set (package:alarm/alarm.dart:76:31)
```

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 8*

**Additional context**
*Nothing*

**Comment by gdelataillade** [comment]
Hi @msh-nayan 

Sorry for the issue, I'll fix it soon. In the meantime, cancel and reschedule your alarms and it should fix the issue.

I'm closing it because duplicated: #74
