### ISSUE TITLE
alarm won't be fired when screen is locked

### ISSUE THREAD

**Issue by whowillcare** [gdelataillade/alarm#108]
**Alarm plugin version**
*ex: 2.1.0 (please update to the latest version before submitting the issue)*

**Describe the bug**
i only tested it on some of the Android phones, alarm won't start if phone screen is locked even the alarm time is passed, as long as you unlock the phone the Alam rings right away.

**To Reproduce**
*Steps to reproduce the behavior:*
1. say set alarm at 1pm around 12:58pm, then lock the screen
2. after 1pm, you won't hear any alarm sound. 
3. at 1:02, you unlock the phone, the alarm starts to go off

**Expected behavior**
*A clear and concise description of what you expected to happen.*
alarm should go off at preset time, no matter if screen is locked or not, as long as app is still running at either background or foreground

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*
android 10 huawei honor, android 13, xiaomi note 10
**Additional context**
*Add any other context about the problem here.*

**Comment by gdelataillade** [comment]
Hi @whowillcare 

That's weird that you are experiencing this issue. Is it happening all the time ?

I'm currently working on a big refactoring of the android part, moving all the code to native code. It will probably fix your issue and you will be able to ring your alarm even if the app was killed.

**Comment by whowillcare** [comment]
yes. It happens all the time.

**Comment by gdelataillade** [comment]
Hi @whowillcare 

I finished working on the big refactoring of the Android part of the plugin.

You can test it on release [3.0.0.dev-2](https://pub.dev/packages/alarm/versions/3.0.0-dev.2).

Let me know if it fixes your issue.

One more thing: if you still have the issue, try to remove battery optimization in you device settings.

**Comment by whowillcare** [comment]
Thank you. Will have a test on it.

**Comment by whowillcare** [comment]
Actually, this version has broken a lot of past dependencies. However, I've managed them migrated. However, it has some hardcode dependency to asset file packages/alarm/assets/not_blank.mp3, which should be happening in my opnion though.

Thank you

**Comment by gdelataillade** [comment]
Indeed I removed some dependencies. This way, I have more control on compatibility, maintainability and plugin's size.

Make sure to follow instruction steps here: https://github.com/gdelataillade/alarm/tree/main/help

I added `not_blank.mp3` in the `.pubignore` so it should not have an impact on the plugin. I use this asset for testing purposes only.

Let me know if you have any questions.

**Comment by gdelataillade** [comment]
Hi @whowillcare 

I just released version `3.0.0`. Let me know if it fixes your issue.

**Comment by singhcreations** [comment]
i want to contact you please help me i am working for ngo i need your help please give me ways to contact you

**Comment by whowillcare** [comment]
Sorry, was on vacation, will take a look the new version soon and give you
a feedback.
