### ISSUE TITLE
Schedule notification with id 0 error: PlatformException(exact_alarms_not_permitted, Exact alarms are not permitted, null, null)

### ISSUE THREAD

**Issue by synstin** [gdelataillade/alarm#114]
**Alarm plugin version**
latest

**Describe the bug**
```
Schedule notification with id 0 error: PlatformException(exact_alarms_not_permitted, Exact alarms are not permitted, null, null)
#0      AlarmNotification.scheduleAlarmNotif (package:alarm/service/notification.dart:147)
<asynchronous suspension>
#1      Alarm.set (package:alarm/alarm.dart:91)
<asynchronous suspension>
```

I found a log of a user experiencing this bug.
I googled the error and stackoverflow told me to add that setting to the manifest file.
https://stackoverflow.com/questions/76309215/unhandled-exception-platformexceptionexact-alarms-not-permitted-exact-alarms
`<uses-permission android:name="android.permission.USE_EXACT_ALARM" />`

Do I need to add the USE_EXACT_ALARM setting?

**Device info**
SM-F916N
Android 13 (SDK 33)

**Comment by gdelataillade** [comment]
Hi @synstin 

What version of the plugin are you using ?

Yes you need to add `USE_EXACT_ALARM` android permission in your manifest. Let me know if it fixes your issue.

**Comment by synstin** [comment]
I am using version 2.1.1.
Is this the way to add it?

```
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>
<uses-permission android:name="android.permission.USE_EXACT_ALARM"/>
```

**Comment by gdelataillade** [comment]
Hi @synstin 

I just released version `3.0.0`. Let me know if it fixes your issue.

**Comment by AwaisQazii** [comment]
@gdelataillade  I'm not being able to receive notification on alarm ringing

**Comment by gdelataillade** [comment]
Hi @AwaisQazii 

Did you give permission for notifications ?

If not, check out [permission_handler](https://pub.dev/packages/permission_handler) to ask permission.

**Comment by gdelataillade** [comment]
I'm closing this issue because I believe asking for permission solved it. Feel free to reopen if you still have the problem.
