### ISSUE TITLE
Consecutive alarm error : mediaplayer went away with unhandled events

### ISSUE THREAD

**Issue by KetutKusuma** [gdelataillade/alarm#117]
**Alarm plugin version**
^3.0.0-dev.5

**Describe the bug**
When i use the alarm ringing for many time with consecutive. this error show up, maybe this is my wrong, can you help me

**To Reproduce**
*Steps to reproduce the behavior:*
1. *...*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
<img width="1048" alt="image" src="https://github.com/gdelataillade/alarm/assets/71806737/70db0f68-8d77-4ea0-a46d-9e2305e61112">

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Additional context**
*Add any other context about the problem here.*

**Comment by gdelataillade** [comment]
Hi @KetutKusuma 

Thanks for reporting the issue.

The issue happens when you schedule multiple alarms at the same time or when multiple alarms ring at the same time ?

I'll try to fix this in the next release.

**Comment by gdelataillade** [comment]
Hi @KetutKusuma 

I just released version `3.0.0`. Let me know if it fixes your issue.

**Comment by KetutKusuma** [comment]
@gdelataillade i want to ask again, can the alarm working on background message?, and stop it on the notification?

**Comment by gdelataillade** [comment]
Hi @KetutKusuma 

What do you mean by "working on background message" ?

Then, for "stop it on the notification", if you refer to notification actions then it's not currently available but I'll develop it someday soon hopefully.
