### ISSUE TITLE
About the vibration function

### ISSUE THREAD

**Issue by tattuu** [gdelataillade/alarm#12]
Thank you so much for publishing this great package!!!

I appreciate it from the bottom of my heart.

We think it would be even better if the alarm had a vibration function.

For example, it would be greatly appreciated if the following items could be added to achieve this.

```dart
final alarmSettings = AlarmSettings(
  // ...
  vibrate: true // this add
);
```

**Comment by gdelataillade** [comment]
Hi @tattuu

Thank you so much for your interest in the package !

I totally agree with you. Adding the vibration feature is on my to-do list, and I will start developing it as soon as I finish with the pull request #11 I am currently working on.

**Comment by gdelataillade** [comment]
What do you think would be the best way to vibrate during the alarm ?

There is this package [vibration](https://pub.dev/packages/vibration) that allows you to set a duration, amplitude and patterns.

**Comment by tattuu** [comment]
Hi @gdelataillade 

Thanks for the reply!

If you don't need to write it in native code and can dependency on flutter, that package is the best choice.

If that package is not available, the implementation method will depend on how far you are willing to go for customizability.

If customizability is to be sacrificed, it may be better to prepare several templates in advance and let the user choose from them.

For example, the enum image is close to the one implemented in this vibration package.
[https://pub.dev/packages/flutter_vibrate](https://pub.dev/packages/flutter_vibrate)

```dart
// Choose from any of these available methods
enum FeedbackType {
  success,
  error,
  warning,
  selection,
  impact,
  heavy,
  medium,
  light
}
```

**Comment by tattuu** [comment]
For example
```dart
final alarmSettings = AlarmSettings(
  // ...
  vibrationFeedbackType: VibrationFeedbackType.heavy // this add
);
```

**Comment by gdelataillade** [comment]
Thanks for your research @tattuu !

I will try to go for customizability as much as possible. An enum can be a good easy-to-use option though !
