### ISSUE TITLE
 Unhandled Exception: PlatformException(NATIVE_ERR, [Alarm] Error loading given local asset path: assests/nokia.mp3, null, null)

### ISSUE THREAD

**Issue by jaffpro** [gdelataillade/alarm#124]
Dear gdelataillade

when i try to add alarm iv'e got these errors
IOS :
 Unhandled Exception: PlatformException(NATIVE_ERR, [Alarm] Error loading given local asset path: assests/nokia.mp3, null, null)
 
 Android :
 java.io.FileNotFoundException: assests/nokia.mp3: open failed: ENOENT (No such file or directory)
 
 this is my code
 
 ` await Alarm.init();

        final alarmSettings = AlarmSettings(
          id: element.id ?? 0,
          dateTime: startDt.subtract(const Duration(minutes: 30)),
          assetAudioPath: "assests/nokia.mp3",
          loopAudio: true,
          vibrate: true,
          volume: 0.8,
          fadeDuration: 3.0,
          notificationTitle: 'You have an interview'.tr,
          notificationBody:
              '${"your interview start on".tr} : \n${DateFormat('d MMM yyyy hh:mm').format(startDt)}',
          enableNotificationOnKill: true,
        );
       var tempAlarm = Alarm.getAlarm(element.id!);
        if (tempAlarm ==null) {
          await Alarm.set(alarmSettings: alarmSettings);
        }`

**Comment by gdelataillade** [comment]
Hi @jaffpro 

Thanks for your feedback.

Are you sure you provided the right asset audio path ? Shouldn't it be `assets/nokia.mp3` ?

**Comment by jaffpro** [comment]
thanks for replay,
yes i am sure , and i try other mp3 files with the same issue
<img width="161" alt="image" src="https://github.com/gdelataillade/alarm/assets/103430060/27382dda-a847-4197-b74a-4f6dace8f987">

<img width="287" alt="image" src="https://github.com/gdelataillade/alarm/assets/103430060/7cde6c66-16b3-46bb-97bc-bfa212367f9a">

**Comment by tattuu** [comment]
Hi @jaffpro 

There's a possibility that upgrading to the latest version (3.0.2) might solve the issue.

I also encountered what seemed to be the same error with Android.
Understood, in my case, it was not a Project asset but a Local asset.

```
W/System.err( 8851): java.io.FileNotFoundException: flutter_assets//data/user/0/xxxx.com/app_flutter/sample_sound.mp3
W/System.err( 8851): 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
W/System.err( 8851): 	at android.content.res.AssetManager.openFd(AssetManager.java:963)
W/System.err( 8851): 	at com.gdelataillade.alarm.services.AudioService.playAudio(AudioService.kt:32)
W/System.err( 8851): 	at com.gdelataillade.alarm.alarm.AlarmService.onStartCommand(AlarmService.kt:96)
W/System.err( 8851): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
W/System.err( 8851): 	at android.app.ActivityThread.access$2100(ActivityThread.java:310)
W/System.err( 8851): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
W/System.err( 8851): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err( 8851): 	at android.os.Looper.loopOnce(Looper.java:226)
W/System.err( 8851): 	at android.os.Looper.loop(Looper.java:313)
W/System.err( 8851): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
W/System.err( 8851): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8851): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
W/System.err( 8851): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

However, after upgrading from version 3.0.0 to 3.0.2, the error no longer occurred.

I apologize if I was mistaken.

**Comment by jaffpro** [comment]
i try to change "assests" folder name to "assets" then it's work,
so we have to use only this name "assets" we can't use other folder name like images,extra,or any name we want
