### ISSUE TITLE
Firebase initialized main.dart and Initialized Alarm.dart not listem message

### ISSUE THREAD

**Issue by abdulsamadshah** [gdelataillade/alarm#127]
**Alarm plugin version**
*ex: 0.2.9 (please update to the latest version before submitting the issue)*

**Describe the bug**
*...*

**To Reproduce**
*Steps to reproduce the behavior:*
1. *...*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Additional context**
*Add any other context about the problem here.*

**Comment by gdelataillade** [comment]
Hi @abdulsamadshah 

Please provide error logs or more information please.
