### ISSUE TITLE
Volume not recovering in the background

### ISSUE THREAD

**Issue by synstin** [gdelataillade/alarm#129]
**Alarm plugin version**
3.0.2

**Describe the bug**
When I'm looking at the screen, when a notification goes off, the volume of the song in the external music player decreases and then returns to its original volume.

However, when the app is in the background or the screen is off, the volume of the song in the external music player decreases when the notification goes off and does not return to its original volume.

When I turn the app back on to the foreground, the volume returns to normal.

**Expected behavior**
When the notification sounds, the song volume should decrease and then recover.

**Device info**
Real device, iPhone 15, iOS 17.2

**Comment by gdelataillade** [comment]
Hi @synstin 

Thanks for sharing your issue.

At what frequency does the issue happens? Every time or just sometimes ?

**Comment by synstin** [comment]
@gdelataillade 

Happens every time. I've only tested it on my iPhone.
Thanks.

**Comment by gdelataillade** [comment]
Hi @synstin 

I just released version `3.0.3` with some Android fixes. Let me know if it fixes your issue.

**Comment by synstin** [comment]
@gdelataillade It works perfectly. Thank you!
