### ISSUE TITLE
Gradual increase in alarm sound volume

### ISSUE THREAD

**Issue by tattuu** [gdelataillade/alarm#13]
Thanks for the great package!

Although it is good to have the alarm sound at maximum volume suddenly, we believe that there are cases where the volume should be increased in stages.

We would be happy if we could choose whether to increase the volume step by step or suddenly turn it up to maximum volume.

For example, we would set it in the following way.
```dart
final alarmSettings = AlarmSettings(
  // ...
  volumeUp: true // this add
);
```

What do you think?

**Comment by gdelataillade** [comment]
Hi @tattuu,

Thank you again for your interest in the package, and for opening your second issue !

You are right, the gradual increase of the alarm sound volume is a feature that would be really useful in some cases. I will let you know when I find the time to develop it.

Don't you think it would be better to pass as parameter a `Duration` that will represent the amount of time the volume will have to go from 0% to 100% ?

**Comment by tattuu** [comment]
Hi @gdelataillade 

Thanks for the reply.

Indeed!!!
`Duration` seems to be more versatile.

We are very happy that you are able to accommodate us.

**Comment by gdelataillade** [comment]
Hey @tattuu !

I found a way to run Swift code on background after a delay. This way, I'm might be able to gradually increment the sound volume.

I'm running some advanced tests at the moment, and if everything is OK then I'll push my code and publish a new release of the package with this new feature.

**Comment by tattuu** [comment]
Hi @gdelataillade 

Really!!!?

Thanks for letting us know!

I'll be waiting in anticipation.
I'll be sure to add you to my app as soon as it's released!

**Comment by gdelataillade** [comment]
Hey @tattuu,

My tests were successful, so I updated the package to the version `0.1.3` including this feature.

I'm closing this issue, but please reopen it or open another one if you see something wrong with the feature. Here's the commit details if you are interested: [Add fadeDuration parameter](https://github.com/gdelataillade/alarm/commit/a6d03eddf34d423ad7237c77e662014a9fc2f178).

**Comment by tattuu** [comment]
Hi @gdelataillade 

Sorry for the late message.

I've been very busy.

I saw the code you created.
And I actually ran ver 1.0.5 and it works fine for this function.

Thanks!
