### ISSUE TITLE
ios archive fails - incl. solution 

### ISSUE THREAD

**Issue by BorisKingma** [gdelataillade/alarm#131]
**Alarm plugin version**
3.0.2

**Describe the bug**
Archive function for IOS fails, while run for device works splendidly.

**To Reproduce**
clean build folder
select build for any device
product- archive

Archive fails, due to phasescript not ending with 0 exit code.
IntermediateBuildFilesPath/UninstalledProducts/iphoneos/alarm.framework" failed: No such file or directory (2)

**Expected behavior**
archive succeeds

**Additional context**
Solution is located here https://stackoverflow.com/questions/75977278/intermediatebuildfilespath-uninstalledproducts-iphoneos-fmdb-framework-failed

**Comment by gdelataillade** [comment]
Hi @BorisKingma 

I was not able to reproduce your issue. I'm not sure it's related to the alarm plugin.

Have you tried to run `pod install --repo-update` in your project's `ios` folder ?

Please let me know if it fixes your archive build.
