### ISSUE TITLE
v3.0.3 bugs - Android

### ISSUE THREAD

**Issue by aykutuludag** [gdelataillade/alarm#133]
**Alarm plugin version**
v3.0.3

**Describe the bug**
Native crash in Android

**To Reproduce**
Nothing. Plugin implemented regularly.

**Expected behavior**
Working without crash.

**Screenshots**
In the comments

**Comment by aykutuludag** [comment]
Hi again! Before releasing new version of my app with v3.0.3 I notice something on Google Play.

<img width="685" alt="Ekran Resmi 2024-01-11 22 33 41" src="https://github.com/gdelataillade/alarm/assets/18382503/e1fd764d-2c58-46c3-b213-98c530ed4157">

It basically suggest switch to inExactAlarm which I used in the past in Native Android (java). Literally no difference between inExact and exact in most situations. In this way, you can reduce permissions in the manifest too.

To get rid of until you release v3.0.4, I found temporary solution. It asks scheduleExactAlarm permission to user Android >=14. If user won't give permission, app will crash most probably either setting alarms or receiving alarm intent.

```
  // TEMPORARY
  if (Platform.isAndroid && await Permission.scheduleExactAlarm.status.isGranted == false) {
    await Permission.scheduleExactAlarm.request();
  }
  // TEMPORARY
```

**Comment by aykutuludag** [comment]
Some early bug reports dropped to Firebase Crashlytics. This error is about vibration in older android versions.

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/VibrationEffect;
       at com.gdelataillade.alarm.services.VibrationService.startVibrating(VibrationService.java:1)
       at com.gdelataillade.alarm.alarm.AlarmService.onStartCommand(AlarmService.java)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3455)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6351)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
```

<img width="1030" alt="Ekran Resmi 2024-01-11 23 26 29" src="https://github.com/gdelataillade/alarm/assets/18382503/efd3202b-4821-4460-b4b0-27d19572d5e7">

**Comment by aykutuludag** [comment]
Another bug only appear in Android >= 14.

```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.gdelataillade.alarm.alarm.AlarmService@efecfc5 with Intent { cmp=app.packagename/com.gdelataillade.alarm.alarm.AlarmService (has extras) }: java.lang.SecurityException: Starting FGS with type mediaPlayback callerApp=ProcessRecord{a25e887 31559:app.packagename/u0a351} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK] 
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5089)
       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2458)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:222)
       at android.os.Looper.loop(Looper.java:314)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
```

My guess is adding following permission to manifest (addition to android.permission.FOREGROUND_SERVICE)  can prevent this error.

`<uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK" />`

**Comment by aykutuludag** [comment]
Appear in Android 12, 13 and 14.

```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.gdelataillade.alarm.alarm.AlarmService@a4b147 with Intent { cmp=app.packagename/com.gdelataillade.alarm.alarm.AlarmService (has extras) }: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service app.packagename/com.gdelataillade.alarm.alarm.AlarmService
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5248)
       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2444)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by aykutuludag** [comment]
In some phones, notification sends I saw it but after a few seconds notification disappear. It is cancelling notification by itself i dont know why. I encountered more than one phones.

**Comment by gdelataillade** [comment]
Hi @aykutuludag 

Thanks again for this valuable feedback.

- **About exact alarm permission**: indeed, you need to ask for permission to use exact alarms starting Android 14.
- **About vibrator error**: I added an Android version check and handled the case where android API < 26.
- **About FOREGROUND_SERVICE_MEDIA_PLAYBACK permission**: I added it to the AndroidManifest. These changes will be added soon in the next release.
- **About notification disappearing**: indeed I made that if `loopAudio` is false, when your audio provided by `assetAudioPath` ends, I consider that alarm is finished then I stop it (which dismiss the notification). Maybe it's not the best I don't know. What is your use case ? What is the behavior you expect exactly ?

**Comment by aykutuludag** [comment]
Hi @gdelataillade 

About your questions:

- I believe that you should change your code exact to inexact because exact is draining battery and %99.99 percent gives same accuracy and result comparing inExactAlarm
- No further comment for that you can handle it.
- No further comment for that too.
- Best use case scenario for any mobile app for alarm functionality: Ring once, show notification on top bar continously until user click the notification or dismiss the notification. If you ring always, user will remove the app nobody wants an app which continusly ringing. Also because of notification's disappear, user can't understand what is the notification and which app send it? Notifications showns only 3-4 seconds.  In brief my suggestions, ring alarm once and dont dismiss notification automatically, because most scenario user click the notification and open app or specific page in the app.


Best regards.

**Comment by gdelataillade** [comment]
@aykutuludag 
Understood. I'll let you know when I'll make a new release. Thank you.

**Comment by aykutuludag** [comment]
> Owner

Thank you for your hard-work. I see that you released v3.0.4 but I desperately need last feature that is notifications **should not auto dismissible**. So I'm waiting v3.0.5 to release new version and I will create bug file for that version, too.

Have a nice day.

**Comment by aykutuludag** [comment]
Same issue: https://github.com/gdelataillade/alarm/issues/121

**Comment by aykutuludag** [comment]
This issue is about setExactAlarm >>> https://github.com/gdelataillade/alarm/issues/102

**Comment by aykutuludag** [comment]
This is about my suggestion above named as **Extra2** https://github.com/gdelataillade/alarm/issues/84

**Comment by gdelataillade** [comment]
Hi @aykutuludag 

- Do you experience significant battery drain ? Are you sure about `inexactAlarm` ? You used it before ? For long durations ?
- Which one is the extra permission ?
- I just release version `3.0.5` with the android notification that stays even if `loopAudio` is false. I did some research and it seems that there is no way to make persistent notifications on iOS.

**Extra 1**: I'm having some trouble when upgrading to Gradle 8.x.x. Someone opened a PR #130 but I was not able to make alarm ring with this configuration. Also, when I increment Gradle version in my `build.gradle` after updating my JDK, I have build errors.

**Extra 2**: I added a comment in the issue to answer your request: https://github.com/gdelataillade/alarm/issues/84#issuecomment-1892429045

**Comment by aykutuludag** [comment]
> Hi @aykutuludag
> 
> * Do you experience significant battery drain ? Are you sure about `inexactAlarm` ? You used it before ? For long durations ?
> * Which one is the extra permission ?
> * I just release version `3.0.5` with the android notification that stays even if `loopAudio` is false. I did some research and it seems that there is no way to make persistent notifications on iOS.
> 
> **Extra 1**: I'm having some trouble when upgrading to Gradle 8.x.x. Someone opened a PR #130 but I was not able to make alarm ring with this configuration. Also, when I increment Gradle version in my `build.gradle` after updating my JDK, I have build errors.
> 
> **Extra 2**: I added a comment in the issue to answer your request: [#84 (comment)](https://github.com/gdelataillade/alarm/issues/84#issuecomment-1892429045)

* I was using my apps. It sends daily notification and weekly notification. If you don't care 3-5 seconds delay (at max), inexact alarm works perfectly. Because inexact alar  you don't wake up system, other apps and android itself wakeup system peridocially and one of the wake ups our inexact alarm triggered. In your current method, you are awaking app periodically. This is generally not recommended unless you are building alarm plugin which have to work at milliseconds scale, maybe. In mobile application usage, most people are looking for plugin which is setting alarm and/or sending notification and its precision is not important in most cases.
* The ones about exact alarm.
* I will check it, I suppose you fixed all the crash in Android, thank you!

**Comment by aykutuludag** [comment]
Now I'm releasing new version with 3.0.5. I will wait new version of library for iOS. I suppose those bugs are still waiting to fix. Have a nice week.

**Comment by aykutuludag** [comment]
Btw, Android app updated with Alarm 3.0.5 and only remaining error in android is following:

```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.gdelataillade.alarm.alarm.AlarmService@2b3568 with Intent { cmp=com.appname/com.gdelataillade.alarm.alarm.AlarmService (has extras) }: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.appname/com.gdelataillade.alarm.alarm.AlarmService
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5261)
       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2447)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by aykutuludag** [comment]
> Btw, Android app updated with Alarm 3.0.5 today. Only remaining error in android is following. I couldn't understand why it gives error:
> 
> ```
> Fatal Exception: java.lang.RuntimeException: Unable to start service com.gdelataillade.alarm.alarm.AlarmService@2b3568 with Intent { cmp=com.appname/com.gdelataillade.alarm.alarm.AlarmService (has extras) }: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.appname/com.gdelataillade.alarm.alarm.AlarmService
>        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5261)
>        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs()
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2447)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8762)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> ```
> 
>  ```
> Caused by android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.appname/com.gdelataillade.alarm.alarm.AlarmService
>        at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
>        at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
>        at android.os.Parcel.readParcelableInternal(Parcel.java:4787)
>        at android.os.Parcel.readParcelable(Parcel.java:4755)
>        at android.os.Parcel.createExceptionOrNull(Parcel.java:3018)
>        at android.os.Parcel.createException(Parcel.java:3007)
>        at android.os.Parcel.readException(Parcel.java:2990)
>        at android.os.Parcel.readException(Parcel.java:2932)
>        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6991)
>        at android.app.Service.startForeground(Service.java:743)
>        at com.gdelataillade.alarm.alarm.AlarmService.onStartCommand(AlarmService.java:152)
>        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5243)
>        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs()
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2447)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8762)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/18382503/297131919-5fb34a2a-8c9c-4a2b-96b6-52abddd41a66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MjU1MjQsIm5iZiI6MTcwNTUyNTIyNCwicGF0aCI6Ii8xODM4MjUwMy8yOTcxMzE5MTktNWZiMzRhMmEtOGM5Yy00YTJiLTk2YjYtNTJhYmRkZDQxYTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDIxMDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYTkzNjE5NzE0YTM4ODkxNmZjZGEyNjg1ZmM4MjNmNWYwNzc1MzVkOTIxOWEwYjRiMjY3M2I5MmQ5MzdhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BeGooKjKSnPN2v4TSAIHvBhIdzuf59m-nQRaie9jAdU)
> 
> I couldn't see any error beside this. Thank you for your effort, have a nice day.
> 
> Note: I guess this error is about https://developer.android.com/develop/background-work/services/foreground-services. You added this permission to Manifest in previous versions, maybe it requires runtime request permission.

This error occurring on Android 12, 13 and 14. I suppose this crash is about this: https://stackoverflow.com/a/70666991/4606368

**Comment by aykutuludag** [comment]
I'm checking everything and releasing new version with 3.0.5 again. I updated flutter and dart sdk, too. I'm closing this issue now, if anything happens on new version, I will create new bug file for Android. For ios current bugs are still valid, no need to open new one. Kind regards.
