### ISSUE TITLE
If alarm is set to ring after 1 month it rings right after Alarm.set - Android

### ISSUE THREAD

**Issue by yaro-melnychuk** [gdelataillade/alarm#136]
**Alarm plugin version**
3.0.5

**Describe the bug**
On Android devices, when setting the alarm `dateTime` for more than 1 month after the current date, the alarm starts immediately.
(Should start in 1 month)

**To Reproduce**
to reproduce on the example app replace [this](https://github.com/gdelataillade/alarm/blob/b251a3ba1d7fef2f22bfd39607aaba6f67fc4792/example/lib/screens/edit_alarm.dart#L92C34-L92C34) line with something like this
`dateTime: selectedDateTime.add(const Duration(days: 40)),`
 
**Expected behavior**
The alarm should ring after 40 days but rings immediately.

**Device info**
Android only

**Comment by gdelataillade** [comment]
Hi @yaro-melnychuk 

Thank you for sharing this issue.

I was able to reproduce your issue. It was caused by an integer overflow of the variable that stored the alarm delay in milliseconds. I just released a fix in version `3.0.6`.

Please let me know if it fixes your issue.

**Comment by melnychuk-yaro** [comment]
worked, thanks

**Comment by gdelataillade** [comment]
Awesome. I'm closing the issue then.

**Comment by kydoaod** [comment]
> Awesome. I'm closing the issue then.

I want to reopen this as I encounter this in version 3.0.8

**Comment by gdelataillade** [comment]
@kydoaod 

Sure, it's reopened. What is the duration you gave ?

**Comment by kydoaod** [comment]
> @kydoaod
> 
> Sure, it's reopened. What is the duration you gave ?

@gdelataillade I did try 1min from now, 7hours from now and 1hour from now but regardless, the outcome is the same. Bug is still there

**Comment by gdelataillade** [comment]
@kydoaod 

Do you have error logs ?

**Comment by kydoaod** [comment]
> @kydoaod
> 
> Your alarm rings immediately regardless of the date time too ?
> 
> Do you have error logs ?

@gdelataillade 

Yes but it does not have any error logs. Its just that the alarm trigger was wrong. By the way, I am using this package as well https://pub.dev/packages/flutter_background_service to overcome the issue about when the app was killed, it wont trigger alarm anymore. And also this package https://pub.dev/packages/awesome_notifications for other matters. Will that be helpful?

**Comment by gdelataillade** [comment]
Hi @kydoaod 

I make alarms with date times in the past ring, to handle the case where an alarm did not trigger for some reason so it can still ring later, when it gets possible.

OK, so I'll let you fix your code. I'm closing this issue again. Send a message here for any other question, I'll see it.
