### ISSUE TITLE
Bug android AndroidAlarm.stop android 13/14

### ISSUE THREAD

**Issue by wayupdev** [gdelataillade/alarm#141]
**Alarm plugin version**
3.0.5

**Describe the bug**
Issue sur crashlytics 

**To Reproduce**
I couldn't reproduce it

**Expected behavior**
Work fine 

**Screenshots**
<img width="1298" alt="image" src="https://github.com/gdelataillade/alarm/assets/124531269/af30e0a0-17f0-4974-ba36-177b8bf355ad">
<img width="1225" alt="image" src="https://github.com/gdelataillade/alarm/assets/124531269/48f90848-1a61-4d4e-8909-3bffcd293121">
<img width="576" alt="image" src="https://github.com/gdelataillade/alarm/assets/124531269/e78c3a1b-4af7-42c2-a320-9f0b50fea8fe">

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Additional context**
AndroidAlarm.stop
io.flutter.plugins.firebase.crashlytics.FlutterError - PlatformException(error, Not allowed to start service Intent { act=STOP_ALARM cmp=com.gdelataillade.alarm.alarm.AlarmService (has extras) }: app is in background uid UidRecord{180ce25 u0a593 TPSL idle change:cached|procstate procs:0 seq(22

package:alarm/src/android_alarm.dart:77

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(error, Not allowed to start service Intent { act=STOP_ALARM cmp=com.gdelataillade.alarm.alarm.AlarmService (has extras) }: app is in background uid UidRecord{85c1e75 u0a422 TPSL idle change:cached|procstate procs:0 seq(14200743,14200327)}, null, android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { act=STOP_ALARM cmp=com.gdelataillade.alarm.alarm.AlarmService (has extras) }: app is in background uid UidRecord{85c1e75 u0a422 TPSL idle change:cached|procstate procs:0 seq(14200743,14200327)} at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1918) at android.app.ContextImpl.startService(ContextImpl.java:1874) at android.content.ContextWrapper.startService(ContextWrapper.java:827) at com.gdelataillade.alarm.alarm.a.onMethodCall(Unknown Source:75) at z9.k$a.a(Unknown Source:17) at n9.c.l(Unknown Source:18) at n9.c.m(Unknown Source:40) at n9.c.i(Unknown Source:0) at n9.b.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8296) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) )

**Comment by aykutuludag** [comment]
I can verify that this issue has been fixed.

**Comment by gdelataillade** [comment]
@aykutuludag 

Awesome, I'm closing the issue then
