### ISSUE TITLE
Bug android AlarmService.onStartCommand android 14

### ISSUE THREAD

**Issue by wayupdev** [gdelataillade/alarm#142]
**Alarm plugin version**
3.0.5

**Describe the bug**
Issue in crashlytics

**To Reproduce**
I couldn't reproduce it

**Expected behavior**
Work fine

**Screenshots**
AlarmService.onStartCommand
android.app.ForegroundServiceStartNotAllowedException - Service.startForeground() not allowed due to mAllowStartForeground false: service com.gdelataillade.alarm.alarm.AlarmService
AlarmService.java:150

<img width="1302" alt="image" src="https://github.com/gdelataillade/alarm/assets/124531269/c1b4ef5d-4031-4bf1-a605-8b3f00a5e01b">

<img width="1217" alt="image" src="https://github.com/gdelataillade/alarm/assets/124531269/14d35c54-2747-4aed-812a-7c3f35d7a7c3">

**Device info**
<img width="583" alt="image" src="https://github.com/gdelataillade/alarm/assets/124531269/f891707e-3a41-407c-83f5-5926b21910bd">

**Additional context**
Fatal Exception: java.lang.RuntimeException
Unable to start service com.gdelataillade.alarm.alarm.AlarmService@835578 with Intent { cmp=com.gdelataillade.alarm.alarm.AlarmService (has extras) }: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.gdelataillade.alarm.alarm.AlarmService

Caused by android.app.ForegroundServiceStartNotAllowedException
Service.startForeground() not allowed due to mAllowStartForeground false: service com.gdelataillade.alarm.alarm.AlarmService

**Comment by aykutuludag** [comment]
I can verify that this issue has been fixed.

**Comment by gdelataillade** [comment]
@aykutuludag 

Awesome, I'm closing the issue then.
