### ISSUE TITLE
Customizable Notification Icon

### ISSUE THREAD

**Issue by juanlabrador** [gdelataillade/alarm#144]
Is it possible to use another icon to notification and not ic_launcher?

Thanks for your work

**Comment by gdelataillade** [comment]
Hi @juanlabrador 

I just released version [4.0.0-dev.3](https://pub.dev/packages/alarm/versions/4.0.0-dev.3) with a the parameter `icon` in `NotificationSettings` class. Please upgrade the package and let me know if it works for you.

I'm closing the issue but feel free to reopen it if you have any other related issues.
