### ISSUE TITLE
Alarm id issue

### ISSUE THREAD

**Issue by rajnishsharma1** [gdelataillade/alarm#146]
**Alarm plugin version**
alarm: ^3.0.7

**Describe the bug**
```
E/flutter (23387): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Alarm id cannot be set smaller than Int min value (-2147483648). Provided: 42
E/flutter (23387): #0      Alarm.alarmSettingsValidation (package:alarm/alarm.dart:104:7)
```

**To Reproduce**
*Steps to reproduce the behavior:*
1. Try setting up an alarm
2. Code:
```
    final alarmSettings = AlarmSettings(
      id: 42,
      dateTime: dateTime,
      assetAudioPath: 'assets/alarm.mp3',
      loopAudio: true,
      vibrate: true,
      volume: 0.8,
      fadeDuration: 3.0,
      notificationTitle: 'This is the title',
      notificationBody: 'This is the body',
      enableNotificationOnKill: true,
    );

    await Alarm.set(alarmSettings: alarmSettings);
```

**Device info**
Vivo, Android 12

**Comment by tattuu** [comment]
same issue here

**Comment by rajnishsharma1** [comment]
@tattuu It seems this issue is introduced in newer version
alarm: ^1.2.1 is not having this issue.

**Comment by pyjserv** [comment]
I encountered the same issue. It was fine in version 3.0.6.

**Comment by JosipDomazetDev** [comment]
This pull request should resolve this issue,  a "-" was missing.
https://github.com/gdelataillade/alarm/pull/148

**Comment by gdelataillade** [comment]
Hi @rajnishsharma1 @tattuu @pyjserv @JosipDomazetDev 

Really sorry about that, it was a silly issue. Thanks @JosipDomazetDev for your PR.

I just released version `3.0.8` with the fix.

**Comment by JosipDomazetDev** [comment]
Thanks for the merge, i just wanna mention it was the PR of @Rest00rer not mine, I just commented on both threads to make sure you see it as soon as possible ^^

**Comment by gdelataillade** [comment]
Alright, then thank you @Rest00rer then !
