### ISSUE TITLE
Play alarm sounds stored locally on device

### ISSUE THREAD

**Issue by adem74** [gdelataillade/alarm#15]
Hello. Is it impossible to choose alarm sound from device?

**Comment by gdelataillade** [comment]
Hello @adem74 ,

What do you mean? From the local files of the device?

**Comment by gdelataillade** [comment]
Hello @adem74 

Thank you for reaching out and for your interest in this package!

At the moment it's only possible to choose alarm sounds from your project's assets, but you're right it could be a good feature to be able to choose alarm sounds from the files of your device.

This feature could be developed using the [file_picker](https://pub.dev/packages/file_picker) package.

Unfortunately, I'm still working on other features at the moment, so I won’t be able to add this one right away. In the meantime, feel free to contribute to the package. If you have any other suggestions, do not hesitate to open another issue.

**Comment by adem74** [comment]
I could not find parameters for this feature for oneshotalarm on web. If you know and insert this parameter to function. I can give path of local sound from device.
Thank you for your helps
