### ISSUE TITLE
v2.1.1 Alarm Ringtone Cannot Ringing If the App Closed

### ISSUE THREAD

**Issue by steveng15** [gdelataillade/alarm#152]
**Alarm plugin version**
v2.1.1

**Describe the bug**
I'm having trouble installing/creating an alarm. I'm using alarm version 2.1.1

When my alarm application is closed/removed from the application history window, the alarm does not sound but displays a notification.
notes: Running background application has been ON.

When my alarm app is not closed/removed it runs normally.
How do I keep the alarm sounding when the app is closed/removed from the app history window?

Thank you.

**Comment by dhaval0122** [comment]
Is this issue resolved in the newer version of the pub? For example, alarm: ^3.0.10. Or are there still issues? I am encountering the same problem with my iOS app.

**Comment by gdelataillade** [comment]
Hi @steveng15 @dhaval0122 

As mentioned in the README, iOS alarms can't ring if the app was killed/terminated manually by the user, because all background processes are terminated and then it is impossible for me to run the code to trigger the alarm.

Please read the README for more information.
