### ISSUE TITLE
Alarm does not stop when Open app again. (app killed)

### ISSUE THREAD

**Issue by goldenmoon67** [gdelataillade/alarm#157]
Alarm plugin version
  alarm: ^3.0.12

Describe the bug
I am using the alarm plugin (thank you so much for this). It works when app killed perfectly. It is ringing but When I click to notification it is not stopped the current alarm. It is always ringing. How can I solve it

Android

**Comment by gdelataillade** [comment]
Hi @goldenmoon67 

Thanks for your interest in the plugin !

You should manually stop the alarm when your app opens after tapping on the notification. This way, it is possible to your alarm to keep ringing and show a ringing screen with a "stop" button, like in the example app. But if you want the alarm to stop directly you can just check if `Alarm.isRinging` on app open, or use the `Alarm.ringStream` to get a stream of the ringing status.

Hope this helps.

**Comment by goldenmoon67** [comment]
Thank you @gdelataillade !
I will ask you one last thing. 
Does Alarm.stopAll() delete scheduled alarms (before they ring)?

**Comment by gdelataillade** [comment]
Hi @goldenmoon67 

Yes, `Alarm.stopAll` will delete all scheduled alarms.

Please don't hesitate if you have any other question !

**Comment by goldenmoon67** [comment]
Okay. Thank you very much @gdelataillade . Awesome job
