### ISSUE TITLE
How do you stop the alarm once it starts ringing?

### ISSUE THREAD

**Issue by deep526** [gdelataillade/alarm#167]
If I click the notification it just takes me back to the app, but ring.dart won't open if I wasn't on the ExampleAlarmScreen before I went off the app. 

Is there a way to allow users to stop the alarm when they press the notification which leads them to the app?

**Comment by gdelataillade** [comment]
Hi @deep526 

In the example app, navigation is triggered thanks to the `ringStream` listener. Make sure to have the listener active or to reopen it when you reopen the app.

Let me know if you have any questions !
