### ISSUE TITLE
Stop one alarm but another alarm with like time first alarm will stop ring

### ISSUE THREAD

**Issue by hiepjozu** [gdelataillade/alarm#169]
**Alarm plugin version**
3.0.14

I shaw new bug when i set multi alarm in one time. when i stop first alarm, another alarm will stop media player but in Debug Console post 1 line alarm stopped. 
I/flutter ( 7401): [Alarm] Alarm with id 82642 stopped

"D/MediaPlayer( 7401): _release native called
D/MediaPlayer( 7401): _release native finished"

2 lines repeat with one alarm i set

**Comment by gdelataillade** [comment]
Hi @hiepjozu 

Thanks for your interest in the plugin !

What Android version are you using ? Also, I'm not sure to clearly understand the issue. Could you explain step by step how to reproduce and what is the expected behavior please ?

**Comment by hiepjozu** [comment]
> Hi @hiepjozu
> 
> Thanks for your interest in the plugin !
> 
> What Android version are you using ? Also, I'm not sure to clearly understand the issue. Could you explain step by step how to reproduce and what is the expected behavior please ?

So I'm using android 12 to see this bug.
for examble: I set 3 alarm in one time, and when 3 alarm ring in one time, I will stop one alarm, and 2 another alarm will stop audio layer. I check debug console it show only one alarm stopped.

**Comment by gdelataillade** [comment]
Hi @hiepjozu 

The plugin does not allow you to schedule multiple alarms for the exact same date time.

Let me know if you have any question.
