### ISSUE TITLE
Notifications not synced with Alarms when adding time instead of picking.

### ISSUE THREAD

**Issue by tiwwwi** [gdelataillade/alarm#17]
The notifications will pop on the minute and the alarms rings on the right time. For example if I call
setAlarm(
DateTime.now().add(const Duration(minutes: 1)),
),

if the user presses the start button at 10:38:30 the notification will show at 10:39:00 and the alarm will play at 10:39:30. My expectations are that both the notification and the alarm will get triggered at 10:39:30

I hope you can fix this because I really love how you have simplified the whole process of setting up a notification with an alarm. I'm using this for a timer in my app.

**Comment by gdelataillade** [comment]
Hi @tiwwwi 

Thank you for your interest in the package ! I'm glad you can use it in your project !

I'm currently working on your issue, it will be fixed by the end of the week. I'll let you know when it's done !

You have the issue just for Android right ?

**Comment by tiwwwi** [comment]
awesome!  thanks!  yes  Android only!  I  haven't tested in ios ..

**Comment by gdelataillade** [comment]
Hi @tiwwwi

I just fixed your issue in the 0.1.5 release, you can update the package in your project.

I'm closing this issue but feel free to reopen it or open another if the problem persists or if you have any other question.
