### ISSUE TITLE
Recurring alarms for Android

### ISSUE THREAD

**Issue by Sesa1988** [gdelataillade/alarm#171]
Hi,

please consider this option just for Android. This option can be ignored for iOS and it would make this package a complete solution without a for need work arounds. 

If someone needs this functionality on iOS he could still implement it by themself but it would be at least clean for Android.

**Comment by gdelataillade** [comment]
Hi @Sesa1988 

OK I will keep this in my mind and add it as soon as I found the time. It's not the priority at the moment, I have some issues to fix first. I close this issue because it's duplicated. I'll keep you updated in #47.
