### ISSUE TITLE
Alarm sound volume is turned down to device media volume when setting more than one alarm 

### ISSUE THREAD

**Issue by syahrisnt** [gdelataillade/alarm#173]
**Alarm plugin version**
*ex: 3.0.6*

**Describe the bug**
*My device's media volume is mute. In my code, i set the AlarmSettings volume to 0.7. When I set one alarm and then kill the app, the sound came out as expected. But when I set two alarms and then kill the app, i can not hear any sound. *

**To Reproduce**
*Steps to reproduce the behavior:*
1. *Set device media volume to zero*
2. *Set two alarms*
3. *Kill the app*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: Samsung S23, android 14.*

**Additional context**
*Add any other context about the problem here.*

**Comment by syahrisnt** [comment]
*edit*

the sound was okay when i did not click the notification. but when i clicked the notification and enter the app, the sound got muted

**Comment by gdelataillade** [comment]
Hi @syahrisnt 

Please upgrade to latest plugin version `3.0.14` and let me know if it works.

**Comment by syahrisnt** [comment]
> Hi @syahrisnt
> 
> Please upgrade to latest plugin version `3.0.14` and let me know if it works.

Hi. Thank you for the reply. I've upgraded to version 3.0.14 but still does not work...

**Comment by syahrisnt** [comment]
I also tried with your example code. It works perfectly fine when I set one alarm. But, when I set more than one and kill the app, alarm got muted.

**Comment by gdelataillade** [comment]
@syahrisnt I'm unable to reproduce your issue. To clarify, with an Android 14 device:

- you scheduled an alarm for 1 minute in the future
- you also scheduled another alarm for 2 minutes in the future
- you kill the app
- when the first alarm rings, you see the notification but you don't hear the audio
- when you tap on the notification, you still don't hear the audio
- if only one alarm is scheduled at the time then the audio will work perfectly

Is that it ?

Does it work if the app was not killed ?
Do you use different `id`s for the 2 alarms?

**Comment by syahrisnt** [comment]
Thank you for the reply 
When i see the notification, i can hear the sound. 
When i tap it, i can not hear the sound.

If i did not kill the app, it works perfectly.
I used two different ids.

**Comment by syahrisnt** [comment]
https://github.com/gdelataillade/alarm/assets/144090364/70f4c4c9-0b58-42ae-8970-0b3f62019ce4

Thank you for the reply
When i see the notification, i can hear the sound.
When i tap it, i can not hear the sound.

If i did not kill the app, it works perfectly.
I used two different ids.

**Comment by gdelataillade** [comment]
Hi @syahrisnt 

Thanks for the video, I was able to reproduce your issue. I'm working on it. I'll keep you updated.

**Comment by syahrisnt** [comment]
Thank you so much!

**Comment by gdelataillade** [comment]
No response for a while, assuming issue is resolved. Closing it now. Feel free to reopen if needed.
