### ISSUE TITLE
Alarm 3.0.14 can't show notification on android

### ISSUE THREAD

**Issue by steveng15** [gdelataillade/alarm#175]
**Alarm plugin version**
Latest version 3.0.14

**Describe the bug**
The alarm does not display notifications when the application is closed in android. However, it still sounds. If i'm using simulator ios, alarm showing notifications when the app is closed (killed). I have tried adding `enableNotificationOnKill`, but it has no effect. Can you help me figure out where the problem might be? 

Is there any code that I need to show you?

**Expected behavior**
Alarm show notification on android.

**Device info**
- Simulator ios iphone 15 pro
- Phone android 13

**Comment by gdelataillade** [comment]
Hi @steveng15 

Make sure to follow the installation steps in the README. Also, have you asked for notification permission ?
Do you have any error logs to share ?

**Comment by steveng15** [comment]
I have followed the README. How to request notification permission?

This is my buildAlarm dan saveAlarm code
<img width="590" alt="Screenshot 2024-04-02 at 10 02 57" src="https://github.com/gdelataillade/alarm/assets/48742816/192e0fba-f7f2-4634-bdb3-b1ac6644f943">

i dont have error logs on my code. If i'm using android and i killed the app, alarm only ringing but don't show notification. But if i'm using simulator ios, alarm showing notification.

**Comment by gdelataillade** [comment]
Hi @steveng15 

Your code looks good to me.

To make sure the notification permission was allowed you can check in your app' settings in the iOS/Android Settings app.
If you need to ask the user to give the notification permission you can take a look at the example code. You should use the https://pub.dev/packages/permission_handler package.

**Comment by steveng15** [comment]
Thanks for helping me. It's works.

notification permission on my phone is not allowed and then i'm allow this permission. I will adding permission handler for user to allow this notification permission. Thanks a lot @gdelataillade

**Comment by steveng15** [comment]
Hi @gdelataillade 

Sry, i have 1 question. In the notification that appears, where can I change the text that appears in the notification?

**Comment by gdelataillade** [comment]
Hi @steveng15 

For the notification that shows when app is killed, make sure to call `Alarm.setNotificationOnAppKillConrent` before calling `Alarm.set`. I recommend to call this just after calling await `Alarm.init`.
Let me know if it works for you.

**Comment by pnilkanth12** [comment]
HI @steveng15 I have same issue in when app killed then alarm not ring even i follow all steps which mention in package setup like all permission, add service in AndroidManifest.xml file

For now I have check in android device only

I used latest alarm package version
`alarm: ^3.0.14`

<img width="975" alt="Screenshot 2024-04-09 at 11 35 07" src="https://github.com/gdelataillade/alarm/assets/42322220/d9d080cf-2375-4554-958f-9371f54df1cd">

<img width="1059" alt="Screenshot 2024-04-09 at 11 55 50" src="https://github.com/gdelataillade/alarm/assets/42322220/7bbf4a40-0ceb-4a6e-83c0-11fd756bd0cd">

Notification & Schedule Exact Alarm Permission is also Granted

<img width="905" alt="Screenshot 2024-04-09 at 12 04 18" src="https://github.com/gdelataillade/alarm/assets/42322220/adfaad25-cd92-4bf6-a481-6e4e35273b6b">

Note, I used
compileSdkVersion 34
targetSdkVersion 34
multiDexEnabled true

Hi @gdelataillade I download your repo example code but still in same not ring alarm after app killed
Please help me when I'm wrong

Thanks @gdelataillade @steveng15 in Advance.

**Comment by gdelataillade** [comment]
Hi @pnilkanth12 

Have you granted the notification permission ?

If yes, please also try to:
- disable battery optimizations in the settings
- grant "schedule exact alarm" permission: see step 5 of android installation steps [here](https://github.com/gdelataillade/alarm/blob/main/help/INSTALL-ANDROID.md)

**Comment by pnilkanth12** [comment]
Hi @gdelataillade 
Yes I have given permission for Notification & Schedule Exact Alarm Permission
and in my mobile battery optimisation is disable but still not working

Here app info screenshot may be you got more idea

![WhatsApp Image 2024-04-09 at 14 03 44](https://github.com/gdelataillade/alarm/assets/42322220/150289bd-421c-439d-b97d-e0cc79632b70)

in app foreground & background it's work perfect but when app killed then not work even not getting notification

**Comment by gdelataillade** [comment]
Hi @pnilkanth12 

That's really weird. Could you try with another device ? This way we could know if the issue comes from the device or not.

**Comment by gdelataillade** [comment]
@pnilkanth12 so you have the ring issue only with the xiaomi phone ?

**Comment by pnilkanth12** [comment]
Hi @gdelataillade 
in Xiaomi phone nothing work when app state is killed and in Samsung phone when app killed then show only notification. not open app like when app foreground or background and alarm ring then show alarm screen open for stop and snooze alarm but not behave this in Samsung phone

**Comment by pnilkanth12** [comment]
Hi @gdelataillade 
Thanks a lot
After enable "Autostart" permission it's working fine

**Comment by gdelataillade** [comment]
> Hi @gdelataillade Thanks a lot After enable "Autostart" permission it's working fine

Good to know. I found this plugin that you could implement in your app to suggest your users to enable the `Autostart` permission:
https://pub.dev/packages/auto_start_flutter

I will also mention it in the plugin's readme.

**Comment by pnilkanth12** [comment]
Yeah that's great 

I have one suggestion to add one more **map** variable in **AlarmSettings** model class 
You can see in my code screenshot that for now I made a little change in this package code and added an extra variable, so suppose if there is any other information you would like to add, like an alarm note, etc., the developer can add in this variable and the alarm time they can get.

**Comment by gdelataillade** [comment]
@pnilkanth12 what is the purpose of passing an "information" to the alarm ? What is the use case ?

**Comment by steveng15** [comment]
> Hi @steveng15
> 
> For the notification that shows when app is killed, make sure to call `Alarm.setNotificationOnAppKillConrent` before calling `Alarm.set`. I recommend to call this just after calling await `Alarm.init`. Let me know if it works for you.

sorry for replying, 

For `Alarm.init()` I stored it in main.dart
This is my main.dart code:
<img width="525" alt="Screenshot 2024-04-17 at 11 39 49" src="https://github.com/gdelataillade/alarm/assets/48742816/ce29d020-283b-43e7-bb41-85e2b1a68414">

Where do I put Alarm.setNotificationOnAppKillContent? Is it when the alarm goes off which is on ring.dart
<img width="585" alt="Screenshot 2024-04-17 at 11 40 31" src="https://github.com/gdelataillade/alarm/assets/48742816/3704c9d2-21fe-4c0e-a1a2-4fabae70a053">

I try use static data for `Alarm.setNotificationOnAppKillContent` and it's not work.
