### ISSUE TITLE
There is a phenomenon that the alarm is triggered and sounds, but the alarm sound is interrupted after the alarm page is opened. (I want to make it interrupted when the user clicks the interruption button.)

### ISSUE THREAD

**Issue by nicelee777** [gdelataillade/alarm#177]
**api version** 3.06 - 3.14

In the sample app, I noticed that the alarm works properly even after the app is forcibly closed (an alarm window appears, and the alarm sound continues until the user clicks the confirmation button). However, when testing my app under development, if the app is forcibly closed, the alarm sound starts at the scheduled alarm time, but it stops when the alarm confirmation window (a page asking for the user's confirmation) appears. What should I check?

**Device info** :
galaxy note20 5G (android 13)

**Comment by gdelataillade** [comment]
Hi @nicelee777 

Make sure you are not calling `Alarm.stop` when showing the confirmation window.
Also, make sure you are not calling `Alarm.set` with the same id, because it will override the current alarm, which will make it stop.

Let me know if it helps and if you have any other question.

**Comment by gdelataillade** [comment]
Hi @nicelee777 

Is your issue the same as in #173 ?

**Comment by nicelee777** [comment]
The symptoms are the same, but in my case, the same symptoms are occurring even if only one alarm is registered.

**Comment by gdelataillade** [comment]
Hi @nicelee777 

I just released version `3.1.2`. Please let me know if it fixes your issue.

**Comment by gdelataillade** [comment]
No response for a while, assuming issue is resolved. Closing it now. Feel free to reopen if needed.
