### ISSUE TITLE
Reschedule alarms on android device reboot

### ISSUE THREAD

**Issue by singhcreations** [gdelataillade/alarm#186]
**Alarm plugin latest version**

**whenever phone is switch off then there is no alarm on alarm time we have to open the alarm app again and again doing the process**

**Comment by gdelataillade** [comment]
Hi @singhcreations 

What you need is to automatically reschedule the alarms on device reboot ?

**Comment by AhsanSarwar45** [comment]
You can use this package to run dart code on device boot: [flutter_boot_receiver](https://pub.dev/packages/flutter_boot_receiver). You can call the code which schedules alarms in the callback function. I created this package for this exact issue in my clock app.

**Comment by gdelataillade** [comment]
This feature has been added to alarm version 4.x.x.

**Comment by jys324** [comment]
Is this feature really working? The alarm doesn't sound after reboot. My version is 4.0.6.

**Comment by jys324** [comment]
> This feature has been added to alarm version 4.x.x.

Is this feature really working? The alarm doesn't sound after reboot. This is version 4.0.6.

**Comment by gdelataillade** [comment]
Please provide your android version.

**Comment by jys324** [comment]
phone: Galaxy Note 10, android version: 12.

**Comment by gdelataillade** [comment]
Did you add this permission in your manifest ?

```xml
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
```

Make sure you followed the [installation steps](https://github.com/gdelataillade/alarm/blob/main/help/INSTALL-ANDROID.md).

**Comment by jys324** [comment]
I already did that. but in my case,  After downloading the package, I changed the version of Flutter shared preferences to 2.2.3 to match my dart version. I confirmed that even if I change the version, it saves well in Flutter. Do you think there's a chance that Kotlin won't be able to retrieve the saved value because of this?

**Comment by gdelataillade** [comment]
I have no idea. Could be possible. Can't you upgrade your dart version ?

Also, depending on the device performance, alarms can take a couple of minutes to be rescheduled after a device reboot.

**Comment by jys324** [comment]
I tried many times to upload the dart version, but failed.
I don't think that's the case for me..

I will try harder first. Thank you for your kind reply!

**Comment by gdelataillade** [comment]
Good luck !

**Comment by jys324** [comment]
I found a solution! I created a BootReceiver.kt file next to kotlin mainActivity.kt in my app folder and added this code and it worked.

(import what you need)
class BootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action == "android.intent.action.BOOT_COMPLETED") {
        
        }
    }
}

I think it would be a good idea to notify others as they may experience this same problem.

**Comment by jys324** [comment]
I found a solution! I created a BootReceiver.kt file next to kotlin mainActivity.kt in my app folder and added this code and it worked.

class BootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action == "android.intent.action.BOOT_COMPLETED") {}
    }
}

I think it would be a good idea to notify others as they may experience this same problem.

**Comment by gdelataillade** [comment]
@jys324 it shouldn't be necessary... the alarm plugin has its own BootReceiver.

**Comment by singhcreations** [comment]
please make feature of repetition of alarm daily because your custom daily
alarm code is not always workable
