### ISSUE TITLE
Stopping a ringing alarm will stop other ringing alarms

### ISSUE THREAD

**Issue by hiepjozu** [gdelataillade/alarm#188]
Alarm plugin version: 3.1.2
Device: Xiaomi A1 
OS: Android 12

Describe the bug:
I using alarm example and set 2 alarm 1 minute apart. When I stop first alarm, second alarm stop ring. Please check videos. 

To Reproduce
1. Run example app
2. set first alarm at 9h36
3. set second alarm at 9h37
4. Waiting first and second alarm ring
5. Stop first alarm and second alarm stop ring

https://github.com/gdelataillade/alarm/assets/46736102/b6f36331-84a5-4113-b896-590735009a20

**Comment by singhcreations** [comment]
TRY WITH DIFFRENT ALARM ID

**Comment by hiepjozu** [comment]
> TRY WITH DIFFRENT ALARM ID

In video clip 2 alarm have 2 diffrent id

**Comment by gdelataillade** [comment]
Hi @hiepjozu 

Did you always have this issue or it's new ?

**Comment by hiepjozu** [comment]
> Hi @hiepjozu
> 
> Did you always have this issue or it's new ?

Yes, I check old version it still have this issue
