### ISSUE TITLE
unable to get ring or vibrate on ring screen 

### ISSUE THREAD

**Issue by singhcreations** [gdelataillade/alarm#189]
**Alarm lates version**

**Describe the bug**
*.unable to get ring on ring screen no vibrate nothing issue is arrise after updating to new version kindly check*

**Comment by gdelataillade** [comment]
Hi @singhcreations 

Please share the steps to reproduce.

**Comment by MeharKaur2399** [comment]
when my phone locked, i got notification on lock screen first i click on open the lock screen then i click notification then i go to ring screen, when i go to ring screen ,sound and volumne gone on ring screen there
