### ISSUE TITLE
Failed Change Title and Body on Notification (Alarm version 3.0.14)

### ISSUE THREAD

**Issue by steveng15** [gdelataillade/alarm#191]
**Alarm plugin version**
3.0.14

**Describe the bug**
I want to change the title and body that comes out when the notification appears. I have used `Alarm.setNotificationOnAppKillConrent` and that didn't work. I placed Alarm.init in the `main.dart` file, this is `main.dart` code:
<img width="525" alt="main" src="https://github.com/gdelataillade/alarm/assets/48742816/79c9c801-5e4d-433c-b067-35a186de2e85">

Where do I put Alarm.setNotificationOnAppKillContent? Is it when the alarm goes off which is on ring.dart
<img width="585" alt="ring" src="https://github.com/gdelataillade/alarm/assets/48742816/eb821606-433d-493f-a239-13d4ca62798c">
I try use static data for Alarm.setNotificationOnAppKillContent and it's not work.

**Expected behavior**
Title and body can be changed according to my expectation. In addition, the flutter icon logo can be removed.

**Screenshots**
![WhatsApp Image 2024-04-26 at 10 23 58](https://github.com/gdelataillade/alarm/assets/48742816/3bd490f1-d96c-4098-a917-64610f571df1)

**Comment by gdelataillade** [comment]
Hi @steveng15 

The `Alarm.setNotificationOnAppKillContent` is for the specific notification that shows when the app gets killed; if you enabled `enableNotificationOnKill` parameter (enabled by default). It should be called just after `Alarm.init`.

For the notification that shows when alarms rings, you have to set the `notificationTitle` and `notificationBody` parameters.

About the Flutter notification icon, I'll take a look at it but how did you setup your app icons ?
