### ISSUE TITLE
how can I remove the flutter icon to the right of the notification?

### ISSUE THREAD

**Issue by rickyricko302** [gdelataillade/alarm#192]
please add parameter for hidden then icon on right notification. Thanks.
![photo_2024-04-29_10-29-40](https://github.com/gdelataillade/alarm/assets/36351625/26c07150-4dbc-43b2-b9bb-5539c4f89ba8)

**Comment by gdelataillade** [comment]
Hi @rickyricko302 

I just released plugin version `3.1.3` where large icon is removed. Please let me know if it works for you.

**Comment by rickyricko302** [comment]
Thank you sir, that solved my problem!
