### ISSUE TITLE
can't stop alarms by swiping away in Android API 33 or earlier; can in API 34, 

### ISSUE THREAD

**Issue by ApplySci** [gdelataillade/alarm#198]
**Alarm plugin version**
3.1.3

**Describe the bug**
Alarms can be stopped by swiping, in a flutter Android app, if API level is 34. However, the alarm cannot be dismissed by swiping if the API level is 33 or earlier.

**To Reproduce**
Run the example in the repository in the Android Emulator in Android Studio.

With an emulated API 34 device, the alarm can be stopped by swiping the notification away.

With an emulated API 33 (or earlier) device, the notification cannot be swiped away.

**Expected behavior**
Swiping the alarm notification terminates the alarm

**Device info**
Using the Android emulator with API levels 28-33 shows the bug. API level 34 behaves as expected. Android Moto phones with API level lower than 34 show the bug.

**Comment by gdelataillade** [comment]
I'm closing this issue because in the meantime version `4.0.0` was released including a significant refactoring of the code and many bug fixes. Feel free to reopen if needed !
