### ISSUE TITLE
Your alarms may not ring  You killed the app

### ISSUE THREAD

**Issue by Zubairpv** [gdelataillade/alarm#202]
**Alarm plugin version**
*ex: 0.2.9 (please update to the latest version before submitting the issue)*

**Describe the bug**
 Your alarms may not ring

You killed the app. Please reopen so your alarms can be rescheduled.

![IMG_20240514_233647](https://github.com/gdelataillade/alarm/assets/130651305/0d3efedd-7c32-4888-9087-72c139db28d1)

**Comment by gdelataillade** [comment]
Hi @Zubairpv 

This is a feature I developed for the package. With the latest updates, it's not useful to have this anymore for Android because alarm will always ring. I recommend to set it like this in your `AlarmSettings`:

```Dart
enableNotificationOnKill: Platform.isIOS
```

**Comment by Zubairpv** [comment]
@gdelataillade alrm not ringing

**Comment by gdelataillade** [comment]
@Zubairpv Please make sure you carefully read the README and followed the installation steps. Do you have any error logs ?

**Comment by Zubairpv** [comment]
In my phone its working but after release apk in my phone its not working

**Comment by Zubairpv** [comment]
Alarm set function is working

**Comment by gdelataillade** [comment]
Did he allowed notifications to show ?

**Comment by Zubairpv** [comment]
Yes

**Comment by Zubairpv** [comment]
If he doesn't allow then he will see the app killed notification?
