### ISSUE TITLE
Make use of Hive over SharedPreferences; make the Alarm class abstract and final, or singleton

### ISSUE THREAD

**Issue by ShadichyDev** [gdelataillade/alarm#210]
**Is your feature request related to a problem? Please describe.**
Hive is much more efficient and strictly typed than SharedPreferences. You should consider moving to Hive
Also, the Alarm class sometimes confuses me with the (). Simple workaround is to make it 'abstract final', or make it singleton class

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gdelataillade** [comment]
Hi @ShadichyDev 

I use `hive` in my other projects and I think the package is awesome but I chose `shared_preferences` for the following reasons:
- more efficient for smaller datasets
- uses native iOS/Android APIs, so useful if one day I need to access data from native code
- uses less dependencies

I'm open to discussion, and if you change my mind I will do the migration.
