### ISSUE TITLE
Alarm Rings Only Once After Enabling Instead of Daily at Set Time

### ISSUE THREAD

**Issue by sadikRizvi31** [gdelataillade/alarm#216]
**Alarm plugin version**
*ex: 3.1.4 
The alarm should ring everyday until and unless I stop it from application but it only ring once. 

Am I missing out on some functions like periodic and interval that other plugins do have ?

**Expected behavior**
Once I enabled the Alarm it should ring at the given time everyday not just once.

**Comment by gdelataillade** [comment]
Hi @sadikRizvi31 

Periodic alarms are not supported yet. Please read: #47 (duplicated)
