### ISSUE TITLE
Alarm.ringStream 刚开始时候监听 无法监听到里面的变化 只有重启才能监听到 

### ISSUE THREAD

**Issue by joe6851** [gdelataillade/alarm#217]
**Alarm plugin version**
*ex: 0.2.9 (please update to the latest version before submitting the issue)*

**Describe the bug**
*...*

**To Reproduce**
*Steps to reproduce the behavior:*
1. *...*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Additional context**
*Add any other context about the problem here.*

**Comment by joe6851** [comment]
2.1.1 是可以的  Alarm.ringStream 刚开始时候监听 无法监听到里面的变化 只有重启才能监听到

**Comment by joe6851** [comment]
2.1.1 是可以的   3.1.0 也不行  我是在initstate 监听的ringStream.listen 
![image](https://github.com/gdelataillade/alarm/assets/152799188/28bc58eb-ca82-4d95-a486-ff57fad6112f)
只有当app 重新打开后才能监听stream 里面

**Comment by gdelataillade** [comment]
I'm closing this issue because in the meantime version `4.0.0` was released including a significant refactoring of the code and many bug fixes. Feel free to reopen if needed !
