### ISSUE TITLE
Is it possible to set the alarm sound to other downloaded audio files besides the ones in assets?

### ISSUE THREAD

**Issue by wann2** [gdelataillade/alarm#218]
It looks like the "assetAudioPath" is only set to the audio that is in the asset.

It would be nice to be able to set the alarm sound to other audio file downloaded by the app and stored in the internal folder of getApplicationDocumentsDirectory().

**Comment by Crash285github** [comment]
i use it like this, and it works well: 

assetAudioPath: "((await getApplicationCacheDirectory()).path)/yourFileName.mp3"


should be the same with the documents dir as well :)
also if you didnt, you need to add android.permission.READ_EXTERNAL_STORAGE to AndroidManifest for it to work

**Comment by gdelataillade** [comment]
It should also work with just:
```Dart
assetAudioPath: 'yourFileName.mp3'
```

**Comment by wann2** [comment]
In case of iOS(iPhone), it seems not work properly.

Unhandled Exception: PlatformException(NATIVE_ERR, [SwiftAlarmPlugin] Failed to load audio for asset: /var/mobile/Containers/Data/Application/E38AF61B-7928-4B53-A167-F6FF3D9/Documents/7051157.m4a, null, null)
IOSAlarm.setAlarm (package:alarm/src/ios_alarm.dart:64:7)

**Comment by gdelataillade** [comment]
Hi @wann2 

Do you use `getApplicationDocumentsDirectory` to get the path ?

**Comment by wann2** [comment]
Yes, I used getApplicationDocumentsDirectory, but it seems not work in iPhone. it happens the error.

**Comment by wann2** [comment]
I just put the music filename in assetAudioPath without the getApplicationDocumentsDirectory path and it works fine. 
Thank you very much.
