### ISSUE TITLE
[ios] After cancelling the alarm with Alarm.stopAlarm the vibration still goes through.

### ISSUE THREAD

**Issue by freakness** [gdelataillade/alarm#22]
The sound and notification are cancelled correctly but the vibration still starts at the specified time.

I believe the below line might be the issue. The vibrate boolean is overwritten when the timeout is reached.

https://github.com/gdelataillade/alarm/blob/6276b15a43104cf5a73f35a42fe3c1940b4d48d7/ios/Classes/SwiftAlarmPlugin.swift#L103

**Comment by gdelataillade** [comment]
Hi @freakness 

Thanks for reporting the issue. I'll fix it very soon.

**Comment by freakness** [comment]
Hi @gdelataillade 

I would do it myself, but I'm not that versed in swift. Thanks for responding quickly, we disabled vibration for now.
