### ISSUE TITLE
Hide Volume Hud when ringing in sielent mode

### ISSUE THREAD

**Issue by Sofstica-Noor-Fatima** [gdelataillade/alarm#220]
is it possible to hide the volume controller that is displaying for a while only when the mobile is in silent mode?

**Comment by gdelataillade** [comment]
Hi @Sofstica-Noor-Fatima 

My initial idea was to add a boolean parameter `showVolumeIndicator` but unfortunately I realized that it is mandatory to always show the indicator, for user experience issues.

**Comment by Sofstica-Noor-Fatima** [comment]
can u please share the source code that how can I remove it from setVolumeMethod inside swift class

**Comment by gdelataillade** [comment]
The code where I change the system volume is in the `SwiftAlarmPlugin.setVolume` but I don't know how to hide the volume indicator. I tried many things but without success...

Please let me know if you find a way to do it !

**Comment by gdelataillade** [comment]
During my research I found these plugin: [volume_controller](https://pub.dev/packages/volume_controller) which has the parameter `showSystemUI`. But when I look in his source code and try to do the same it doesn't work.
