### ISSUE TITLE
 Alarm Package Automatically Adds Deprecated USE_FULL_SCREEN_INTENT Permission

### ISSUE THREAD

**Issue by AbdullahMobologics** [gdelataillade/alarm#225]
Description:
Android has recently updated its guidelines to handle the android.permission.USE_FULL_SCREEN_INTENT permission automatically, and it is no longer necessary to specify this permission in the AndroidManifest.xml file. However, even after removing this permission from my AndroidManifest.xml, I noticed that the alarm package is automatically adding it back. This issue came to my attention when I was deploying my app to the Google Play Store for Android.

Steps to Reproduce:

Remove the android.permission.USE_FULL_SCREEN_INTENT permission from AndroidManifest.xml.
Build and deploy the app to the Google Play Store.
Observe that the permission is added back automatically by the package.
Expected Behavior:
The package should not add the android.permission.USE_FULL_SCREEN_INTENT permission automatically.

Actual Behavior:
The package automatically adds the android.permission.USE_FULL_SCREEN_INTENT permission, which is no longer required to be specified in the AndroidManifest.xml.

Additional Information:
Android team has stated that they will handle the USE_FULL_SCREEN_INTENT permission automatically, so there is no need to add this permission manually. Please update the package to stop adding the android.permission.USE_FULL_SCREEN_INTENT permission automatically.

**Comment by gdelataillade** [comment]
Hi @AbdullahMobologics 

Thanks for your interest in the package.

> Android team has stated that they will handle the USE_FULL_SCREEN_INTENT permission automatically, so there is no need to add this permission manually.

Could you share the link please ? When I make sure I can remove this permission then I'll publish a new release as soon as possible.

Also, this issue is duplicated. You can find a workaround here using `tools:node="remove"`: #222 
Let me know if you have any issue with it.
