### ISSUE TITLE
Flutter 3.24 error on flutter_fgbg dependency

### ISSUE THREAD

**Issue by hafidzaini** [gdelataillade/alarm#228]
**Alarm plugin version**
*ex: 0.2.9 (please update to the latest version before submitting the issue)*
Alarm version 3.1.5

**Describe the bug**
*...*
failed to build after updating flutter to 3.24

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_fgbg:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Volumes/external/App/ff/build/flutter_fgbg/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.

**To Reproduce**
*Steps to reproduce the behavior:*
1. *...*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Additional context**
*Add any other context about the problem here.*

Dart SDK 3.5.0
Flutter SDK 3.24.0
ff 1.0.0+1
├── alarm 3.1.5
│   ├── flutter_fgbg 0.3.0
│   │   └── flutter...

latest Alarm plugin use flutter_fgbg 0.3.0
latest version of this dep is 0.4.0

would you please check if using latest version will solve Flutter 3.24 build error?

**Comment by hafidzaini** [comment]
oh sorry,
they get error too
https://github.com/ajinasokan/flutter_fgbg/issues/21

**Comment by elio1fiore** [comment]
hi, can i update flutter_fgbg?
I can't build because of the bugs that were just fixed in 0.6.0 This project is stuck at 0.3.0

**Comment by gdelataillade** [comment]
Hi @elio1fiore 

I just updated the plugin to version `3.1.6` with `flutter_fgbg 0.6.0`. Thanks for reporting the issue.
