### ISSUE TITLE
Remove notification after click it from status bar or notification in app

### ISSUE THREAD

**Issue by songtoanht** [gdelataillade/alarm#231]
**Alarm plugin version**
*ex: 3.1.4

**Describe the bug**
- On Android, the notification doesn't removed when I click it

**To Reproduce**
*Steps to reproduce the behavior:*
1. Open app
2. Set Alarm
3. show notification
4. click notification
5. Notification was not removed

**Expected behavior**
- I want to have a listener or a function return call after click notification to I can cancel or stop it.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
Android device

**Additional context**
*Add any other context about the problem here.*

**Comment by songtoanht** [comment]
Hi @gdelataillade,
After I upgrade to version 4.0.0-dev.1, do I need to modify any other code?

**Comment by gdelataillade** [comment]
Hi @songtoanht 

No, after upgrading to version 4.0.0-dev.1, you shouldn't need to modify any code.

But for 4.0.0-dev.3 I'm modifying the AlarmSettings class so you will need to change a few things but your linter will tell you.
