### ISSUE TITLE
Avoid triggering an alarm if another alarm is already ringing

### ISSUE THREAD

**Issue by razvanghel** [gdelataillade/alarm#232]
When an alarm is already ringing, and another alarm is scheduled to ring while the first alarm is still ringing, both alarms will ring. This can lead to confusion and synchronization issues.

To address this issue, I propose the following solution: an alarm should only ring if no other alarm is currently ringing. This way, if one alarm is already active, it will prevent any subsequent alarms from ringing until the current one has finished. This ensures that each alarm gets the attention it deserves without overlap, providing a clearer and more manageable alert system.

**Comment by gdelataillade** [comment]
Hi @razvanghel 

I just released version [4.0.0-dev.3](https://pub.dev/packages/alarm/versions/4.0.0-dev.3) with a fix for your issue. Please upgrade the package and let me know if it works well for you. Be careful with breaking changes.
