### ISSUE TITLE
On background alarm notification click app doesnot open AlarmRingScreen (any specific screen ) i am trying example code which is in this plugin

### ISSUE THREAD

**Issue by ArisChoice** [gdelataillade/alarm#235]
**Alarm plugin version**
latest one 3.1.7

**Describe the bug**
*...*

**To Reproduce**
*Steps to reproduce the behavior:*
1. Set alarm on ios
2. Close app completely
3. Click on alarm notification (no audio)
4. On notification click app open home screen (needs to open alarm ringing screen)

*** if app is in background its working fine.

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Additional context**
*Add any other context about the problem here.*

**Comment by gdelataillade** [comment]
Are you testing on iOS or Android ?

**Comment by gdelataillade** [comment]
Is it a new issue from the latest version ?

**Comment by dhavalmnjtech** [comment]
also i have to redirect to alarm screen on notification tap.

**Comment by ArisChoice** [comment]
> Is it a new issue from the latest version ?

yes it is in latest as well as in old versions

**Comment by ArisChoice** [comment]
> Are you testing on iOS or Android ?

ios working fine  in android

**Comment by gdelataillade** [comment]
Hi @ArisChoice @dhavalmnjtech 

OK thanks, and with which Android versions are you experiencing the issue ? And with which manufacturers (Android, OnePlus, ...) ?

**Comment by ArisChoice** [comment]
> Hi @ArisChoice @dhavalmnjtech
> 
> OK thanks, and with which Android versions are you experiencing the issue ? And with which manufacturers (Android, OnePlus, ...) ?

for me issue is with ios  its working fine inn android

**Comment by gdelataillade** [comment]
Hi @ArisChoice @dhavalmnjtech 

Do you still have the problem ?

Someone else reported the issue: #241 

I'm closing this thread, let's talk in the new issue. Thanks.
