### ISSUE TITLE
Custom notification Icon.

### ISSUE THREAD

**Issue by dhavalmnjtech** [gdelataillade/alarm#237]
**Alarm plugin version**
latest one 4.0.0-dev.2
I need stop button in notification that's why i used this version

**For my app, I have to set custom icon for notification instead of my app icon**

**You can**
provide any property or AndroidManifest.xml configuration to change alarm notification icon

**Comment by gdelataillade** [comment]
Hi @dhavalmnjtech 

I just released version [4.0.0-dev.3](https://pub.dev/packages/alarm/versions/4.0.0-dev.3) with a the parameter `icon` in `NotificationSettings` class. Please upgrade the package (with breaking changes) and let me know if it works for you.

**Comment by dhavalmnjtech** [comment]
![image](https://github.com/user-attachments/assets/eef91d16-0ba3-489e-a1ca-f57e7b89969d)

**Comment by dhavalmnjtech** [comment]
Thanks for making this so soon.
