### ISSUE TITLE
loopVibrate option? 

### ISSUE THREAD

**Issue by tiwwwi** [gdelataillade/alarm#24]
I think the vibrate should follow  the loopAudio  or have its own loopVibrate option?  
For now if I set my alarm to ring once it will ring once but the vibrate keeps on going.  I think the vibrate should also just vibrate once or twice.

**Comment by gdelataillade** [comment]
Yes @tiwwwi you're right.

In the case I'm able to get the audio duration, don't you think it would be more relevant to vibrate until the audio ends ?

**Comment by gdelataillade** [comment]
Fixed in `0.2.7`.

**Comment by gdelataillade** [comment]
Let me know if it's working as expected @tiwwwi

**Comment by tiwwwi** [comment]
Very nice,  it follows the same timeline as the alarm sound length!!  C'est parfait! Merci ;)

**Comment by gdelataillade** [comment]
Super ! De rien ☺️
