### ISSUE TITLE
Alarm vibrate non-stop

### ISSUE THREAD

**Issue by loinguyen10** [gdelataillade/alarm#242]
Alarm plugin version:
4.0.0-dev.2 (this bug was happening ever since i tried 3.1.5)

Describe the bug
The alarm is vibrating for too long.

Expected behavior
Is there a way to limit the vibration time, like set minute vibrating and then automatically calling alarm.stop or alarm.snooze?

Device info
Both device

Additional context
Hope you can downgrade shared_preferences to 2.2.3 in dev-version due to some reason I can't upgrade dart version more than 3.3, sorry about that 😅. Great plugin.

**Comment by gdelataillade** [comment]
Hi @loinguyen10 

If you set the loop param to false, then the alarm will stop ringing and stop vibrating when the alarm audio ends. For example if you have a 30 seconds long audio then after 30 seconds the alarm will stop automatically.

About downgrading shared_preferences, sorry I can't do that. What you could do is to manually downgrade it in plugin's code.

Let me know if you have any questions.
