### ISSUE TITLE
Not Working when phone restarted between the Scheduled Alarm

### ISSUE THREAD

**Issue by saty-a** [gdelataillade/alarm#243]
**Alarm plugin version**
*ex: 0.2.9 (please update to the latest version before submitting the issue)*

**Describe the bug**
Not Working when phone restarted between the Scheduled Alarm.

**To Reproduce**
Setup alarm for a particular time and then restart the phone between that time.
Then if you will see that no notification will come on top of the screen.
1. *...*

**Expected behavior**
It should provide the notification even when phone is restarted.

**Screenshots**
Not Applicable

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Comment by gdelataillade** [comment]
Hi @saty-a 

Please provide more information. I added the alarm reschedule after reboot on android on version `4.0.0-dev.4`. Have you tried this version ?

**Comment by saty-a** [comment]
I've updated to 4.0.0-dev.4 and it's working for android Thanks for notifying!!
