### ISSUE TITLE
when tap cancel alarm button so redirect to ring screen this is wrong

### ISSUE THREAD

**Issue by BhautikVaghasiya** [gdelataillade/alarm#259]
when tap the cancel alarm button so redirects to ring screen this is the wrong
 @override
  void initState() {
    super.initState();
    AlarmPermissions.checkNotificationPermission();
    if (Alarm.android) {
      AlarmPermissions.checkAndroidScheduleExactAlarmPermission();
    }
    loadAlarms();
    ringSubscription ??= Alarm.ringStream.stream.listen(navigateToRingScreen);
    updateSubscription ??= Alarm.updateStream.stream.listen((_) {
      loadAlarms();
    });
  }

**Comment by gdelataillade** [comment]
Provide steps to reproduce please.

**Comment by BhautikVaghasiya** [comment]
how to write code if cancel alarm button tap so so not redirect to ring screen.

**Comment by gdelataillade** [comment]
I don't understand. If you want to run code when alarm rings then modify the `navigateToRingScreen` callback.

**Comment by BhautikVaghasiya** [comment]
how to possible alarm ring ontap to handle navigator screen.?

**Comment by BhautikVaghasiya** [comment]
ringSubscription ??= Alarm.ringStream.stream.listen(navigateToRingScreen);
if user tap to cancel alarm button so not navigateToRingScreen.

**Comment by gdelataillade** [comment]
In the example app, the cancel button means that you want to cancel the editing or creating of the alarm. If you want to cancel the alarm you have to press the stop button.

**Comment by BhautikVaghasiya** [comment]
https://github.com/user-attachments/assets/fde7afc4-3ffc-4ce7-832b-e4c3d2d8f613

https://github.com/user-attachments/assets/fe4a74cf-fa74-4802-8579-3d3369844c69
how to change font size. recived alarm notification.

**Comment by gdelataillade** [comment]
Ok I understand now. 

You need to listen for the `Alarm.updateStream` and in its callback you need to check if an alarm is ringing. If not, then navigate back to your home screen.

**Comment by BhautikVaghasiya** [comment]
https://github.com/user-attachments/assets/fe4a74cf-fa74-4802-8579-3d3369844c69
how to change font size. recived alarm notification.

**Comment by gdelataillade** [comment]
No, it is not possible (tell me if I'm wrong) to change the font size of the notification action buttons. The action buttons in notifications have a fixed style defined by the system and cannot be customized.

**Comment by BhautikVaghasiya** [comment]
Alarm.updateStream and in its callback you need to check if an alarm is ringing. If not, then navigate back to your home screen.
how to check alarm is ringing ?please write code

**Comment by gdelataillade** [comment]
Use `Alarm.isRinging` method.

**Comment by gdelataillade** [comment]
Set this:

```Dart
updateSubscription ??= Alarm.updateStream.stream.listen(onAlarmsUpdate);
```

with callback:

```Dart
  Future<void> onAlarmsUpdate(int id) async {
    loadAlarms();

    var isAnyAlarmRinging = false;
    for (final alarm in alarms) {
      final alarmIsRinging = await Alarm.isRinging(alarm.id);
      if (alarmIsRinging) {
        isAnyAlarmRinging = true;
        break;
      }
    }

    if (mounted && !isAnyAlarmRinging && Navigator.canPop(context)) {
      Navigator.pop(context);
    }
  }
  ```
