### ISSUE TITLE
iOS: Alarm.isRinging(alarmId) is FALSE after alarm rings

### ISSUE THREAD

**Issue by orkun1675** [gdelataillade/alarm#265]
**Alarm plugin version**
4.0.7

**Describe the bug**
After the alarm rings calling `Alarm.isRinging(alarmId)` returns false. This happens about 30% of the time.

**To Reproduce**
1. Set an alarm
2. Listen for `Alarm.ringStream.stream`
3. When an event fires in this stream, call Alarm.isRinging(alarmId)`
4. PS: At this point our code schedules a timer to repeat 3 every 1s to figure out when the alarm is stopped by the user

**Expected behavior**
`Alarm.isRinging(alarmId)` should continue to return to until the alarm is stopped. 

**Screenshots**
N/A

**Device info**
iPhone SE, iOS 18.0.1, physical device

**Additional context**
Note that the `Alarm.updateStream.stream` is also buggy and can't be used right now to identify when active alarms are stopped. For instance; [the set function](https://github.com/gdelataillade/alarm/blob/main/lib/alarm.dart#L73) returns too early and never populates the stream on line 88.

**Comment by gdelataillade** [comment]
I’ve just released version `4.0.8` with a fix. Please let me know if it resolves the issue. Thanks!

**Comment by gdelataillade** [comment]
By the way, `id` is now optional:

```Dart
Future<bool> isRinging([int? id])
```

> If no `id` is provided, it checks if any alarm is ringing.
> If an `id` is provided, it checks if the specific alarm with that `id`

**Comment by gdelataillade** [comment]
I'm not sure to understand the issue. Is it because `Alarm.isRinging` returns `false` immediately after calling `Alarm.set` ?

**Comment by orkun1675** [comment]
>  Is it because Alarm.isRinging returns false immediately after calling Alarm.set ?

Yes, exactly.

After working on a PR I have seen that we are using `AVAudioPlayer.isPlaying` to check if an alarm is active. However, doesn't this return `false` while the audio file is being loaded by `AVAudioPlayer. prepareToPlay`? Maybe this is causing a race condition?
