### ISSUE TITLE
iOS: Notification is not dismissed after the alarm is stopped

### ISSUE THREAD

**Issue by orkun1675** [gdelataillade/alarm#266]
**Alarm plugin version**
4.0.7

**Describe the bug**
When the alarm is stopped the notification remains visible in the notification center. Notifications actually remain indefinetly until the user clears them (my device had 5 day old Alarm is ringing notifications).

**To Reproduce**
1. Schedule an alarm
2. Wait for alarm to ring
3. Stop the alarm by calling `Alarm.stopAll()`
4. Check notification. center

**Expected behavior**
Ideally, notifications are auto dimissed once the alarm is stopped as they no longer serve a purpose.

**Screenshots**
N/A

**Device info**
iPhone SE, iOS 18.0.1, physical device

**Additional context**
N/A

**Comment by gdelataillade** [comment]
I’ve just released version `4.0.8` with a fix. Please let me know if it resolves the issue. Thanks!

**Comment by orkun1675** [comment]
I can verify this is working now. Thanks!
