### ISSUE TITLE
White Notification Icon Issue

### ISSUE THREAD

**Issue by synstin** [gdelataillade/alarm#278]
**Alarm plugin version**
3.1.7
4.0.9

**Describe the bug**
I've encountered an issue with notification icons being forcibly displayed in white, regardless of the configured icon settings.

The issue appears to be consistent across both older (3.1.7) and the latest (4.0.9) versions
Custom drawable implementations are also affected by this behavior

- Related Issue
https://github.com/gdelataillade/alarm/issues/54

**Steps to Reproduce**
1. Set up an alarm notification
2. Wait for the alarm to trigger
3. Observe the notification icon in the status bar

**Current Behavior**
The notification icon appears in white color only
This behavior persists even after: Updating to the latest version (4.0.9)
Using custom images placed in the drawable directory

**Device info**
Pixel 8 Pro on Android 15
Pixel 7 Pro on Android 14

**Comment by Ketan-Satani-Innovuratech** [comment]
I am still experiencing the white icon issue while using version 5.1.4. I have tested on multiple devices, and all of them display a white icon.

This issue occurs on Pixel devices, emulators, Redmi phones, and Samsung devices.


|      ![Image](https://github.com/user-attachments/assets/2a1d9a3a-7dc9-4901-9db2-5ebfd8ee21f6)            |         ![Image](https://github.com/user-attachments/assets/5a20e328-7e18-48e7-8a1d-2c6986aedf4c)       |
-----------|----------

**Comment by gdelataillade** [comment]
Have you set your icon in `AlarmSettings.NotificationSettings` ?
