### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Musta-Pollo** [gdelataillade/alarm#28]
![New Note](https://user-images.githubusercontent.com/68862752/230727284-b48ffd3a-1af3-4d69-beba-eefe7104591a.jpeg)

Every time I start a timer, I must stop all current alarms (even if they are inactive). The error probably happens here. Different code affection this I don't think that ran at that time. This error crashed the application.

```
await Future.wait(TimerType.values.map((e) async => await Alarm.stop(e.id))); // stops all alarms related to a timer
await Alarm.set(alarmSettings: alarmSettings);
```
In the `alarmSettings` is an id stopped on the previous line.

This is where it crashes in the plugin. I assume that the value passes through the check, but in the meantime, the alarm at that index is stopped. Maybe the await doesn't work.
```
if loopAudio {
      self.audioPlayers[id]!.numberOfLoops = -1
 }
```

I am sorry, but I cannot create a pull request as I have no idea how to do that.

**Comment by gdelataillade** [comment]
Hi @Musta-Pollo 

Thanks for reporting this issue.
I'll take a look at it very soon.

**Comment by gdelataillade** [comment]
Hey @Musta-Pollo 

Which version of the plugin are you using ?

In the `0.2.7` release, a change was added that fixed an issue that looked very similar to yours. [Here's the commit.](https://github.com/gdelataillade/alarm/commit/76bd060e4ee46b8aa148d2c53c9e6c8fcde9c280)

This fixes the case where an invalid audio asset is given.

Please update the dependency to the latest version, double check your asset path and then let me know if you still have the issue.

Check out the iOS installation guide to help you with the import of your assets. It's a bit tricky for iOS:
https://github.com/gdelataillade/alarm#ios-installation-steps

**Comment by Musta-Pollo** [comment]
Hi @gdelataillade, thank you for quickly looking at the issue.

I was looking at this, but I didn't though it related. I never had problems with setting up the audio asset. I followed the tutorial, and all worked smoothly. I had only this problem once. Still, I thought it necessary to report it as crashing is a big problem.

At that time, I had a version `alarm: ^0.2.3`. After the error, I upgraded to the latest version, `alarm: ^0.2.9`, and didn't encounter the error yet. It seems more like an edge case or race condition.

```
private func stopAlarm(id: Int, result: FlutterResult) {
     .......
      self.audioPlayers.removeValue(forKey: id) //there the audio player is removed
  }
```

```
  private func setAlarm(call: FlutterMethodCall, result: FlutterResult) {
  ....
    if loopAudio {
      self.audioPlayers[id]!.numberOfLoops = -1. // Before you check if it exists, but is it possible that the stopAlarm function can modify the self.audioPlayers in the meantime even with the await?
    }
  .....
  }
```

**Comment by gdelataillade** [comment]
@Musta-Pollo You totally right, a crash is a big problem. Thank you again for reporting the issue, I really appreciate it.

The `loopAudio` condition is supposed to be ran instantly at the moment the alarm is set (the code here is synchronous), so its alarm player is never supposed to be null. I hope your issue is definitely fixed in the latest versions.

If the error happens again, please let me know. In that case, it will be necessary to add a null check for the player.

**Comment by Musta-Pollo** [comment]
Thank you for understanding my point of view and explanation. 

Ok, let it be so.
