### ISSUE TITLE
Error: The argument type 'bool' can't be assigned to the parameter type 'String?'.

### ISSUE THREAD

**Issue by louwers** [gdelataillade/alarm#280]
`stopButton` of `NotificationSettings` seems to take a String? not a boolean (like in the README).

**Comment by gdelataillade** [comment]
Hi @louwers 

Thanks for reporting the error. You're right, stopButton takes a String?. It used to take a boolean but I thought it was more useful to take a String?. This is what the documentation says:

```Dart
  /// The text to display on the stop button of the notification.
  ///
  /// Won't work on iOS if app was killed.
  /// If null, button will not be shown. Null by default.
  final String? stopButton;
  ```

I'll fix the README, thanks.
