### ISSUE TITLE
A must needed and very required stop alarm functionality needed other then Notification stop button 

### ISSUE THREAD

**Issue by MuhammadHarisSiddiqui620** [gdelataillade/alarm#291]
Hey there, is Auto stop alarm sound after dismiss notification implemented? Because there is only way the alarm gets stop. That is only when pressing the stop button in the notification. if the notification somehow disappear. The alarm will still ring and user has to uninstall the app in that case to stop the alarm which is a very bad impression.

Can someone confirm that the functionality is added ?

**Comment by gdelataillade** [comment]
Hi @MuhammadHarisSiddiqui620,

Dismissing the notification currently won’t stop the alarm, as this feature hasn’t been implemented yet.

However, pressing the stop button on the notification should stop the alarm. If it’s not working for you, please ensure you’ve followed the installation steps outlined in the README and are using the latest version of the package.

**Comment by gdelataillade** [comment]
Hi @MuhammadHarisSiddiqui620 

The user can also open the alarm app to stop it manually right ?

But yes I know I need to implement this feature. It's in my to do list.

**Comment by gdelataillade** [comment]
I’m closing this issue as it is a duplicate. You can track the progress and updates on the original issue: #207. Feel free to subscribe to it for notifications on any new developments.
