### ISSUE TITLE
[Android] Kotlin naming conflict is leading to compile errors

### ISSUE THREAD

**Issue by orkun1675** [gdelataillade/alarm#299]
I realized that when doing the Pigeon migration I  should have specified a Kotlin package in Pigeon settings. Without this if this plugin is used together with another plugin that uses Pigeon compile time errors will arise.

The fix is simple: add `KotlinOptions(package: 'com...` at https://github.com/gdelataillade/alarm/blob/c62bcfdd2b7d0862da63fe0fadb004d34bfd839a/pigeons/alarm_api.dart#L13 and refactor Kotlin imports.

**Comment by gdelataillade** [comment]
Hi @orkun1675, I made this PR #300 to fix this issue. If it looks good to you I'll merge it.
