### ISSUE TITLE
Sound not working when app killed in ios

### ISSUE THREAD

**Issue by Jassa25** [gdelataillade/alarm#3]
Hello ,

I have implemented it and its working great in background and foreground. But it don't work when app killed in ios. Can you please let us know an solution.

**Comment by gdelataillade** [comment]
Hello @Jassa25,
Thanks for your interest for the package.
Unfortunately, when the app is killed, there is now way the alarm could ring.
We don't have a permanent solution in mind. However, we are developing a workaround that will show a notification at the moment the user kills the app saying something like "Please reopen the app. The alarm will not be able to ring if the app is killed". This way, I hope the user will understand and reopen the app so the alarm could work normally.
We are also thinking about the case where the user ignore this warning: we may replace the alarm audio with several notifications with sound in a row. This is how the app _Alarmy_ works. What do you think ?
One more thing, do you have this issue with Android too ?

**Comment by gdelataillade** [comment]
The version 0.1.0 has been released with a workaround for this issue. The workaround is the one described in my previous message in this issue, on Jan 11. As a result, I'm closing this issue. Feel free to reopen it or open another one if you have any other question.
