### ISSUE TITLE
Alarm sound is not working for me(android), only notification tune works

### ISSUE THREAD

**Issue by MohammedMutasemHamed** [gdelataillade/alarm#32]
**Alarm plugin version**
*ex: 0.2.9 (please update to the latest version before submitting the issue)*

**Describe the bug**
*...*

**To Reproduce**
*Steps to reproduce the behavior:*
1. *...*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Additional context**
*Add any other context about the problem here.*

**Comment by gdelataillade** [comment]
Hi @MohammedMutasemHamed 

Can you provide more information please ?

- What is your device ?
- Which Android version ?
- The app was in foreground or background ?
- How long between the moment you scheduled the alarm and the moment the alarm was supposed to ring ?
- Which version of the alarm plugin are you using ?

It will help me a lot to identify the issue. Thank you in advance.
