### ISSUE TITLE
Get current active alarms

### ISSUE THREAD

**Issue by Joe15975** [gdelataillade/alarm#34]
I found it hard to get active alarms

**Comment by gdelataillade** [comment]
Have you tried to call `Alarm.getAlarms()`. It will return a list of `AlarmSettings` with all the informations about the active alarms.

**Comment by gdelataillade** [comment]
Yes I could add this method if you want. I'll add it soon.

**Comment by Joe15975** [comment]
Work ! Thanks. TawfikOn 14 Apr 2023, at 9:12 AM, Gautier de Lataillade ***@***.***> wrote:﻿
Have you tried to call Alarm.getAlarms() ?
It will return a list of AlarmSettings with all the informations about the active alarms.

**Comment by sandamil** [comment]
> Yes I could add this method if you want. I'll add it soon.

this is working, thanks¡¡¡
