### ISSUE TITLE
[Android] Alarm sound is dependent on the "Media volume" but there is a seperate volume called "Alarm volume"

### ISSUE THREAD

**Issue by dtkdt100** [gdelataillade/alarm#37]
Alarm sound is dependent on the "Media volume" but there is a seperate volume called "Alarm volume", sometimes there is a need to play alarm with sound even when the media volume is down, like native alarm clock.

Checkout: https://github.com/ryanheise/audio_session.

Please make it an option and it will almost like native alarm clock!

It's not hard. Just add this:

```dart
final session = await AudioSession.instance;
    await session.configure(const AudioSessionConfiguration(
      androidAudioAttributes: AndroidAudioAttributes(
        usage: AndroidAudioUsage.alarm,
      ),
    ));
```

**Comment by gdelataillade** [comment]
Good point. I could add a `maxVolume` optional parameter. Thanks !

**Comment by gdelataillade** [comment]
Hey @dtkdt100

I was working on this feature and I realized that due to privacy reasons, there is no official way to change device alarm volume in iOS. I really want the `alarm` plugin to have the exact same behavior for Android and iOS so I will probably not add this feature.

I am adding this to the README FAQ:

> ### Why isn't my alarm ringing when the device volume is off?
> 
> iOS prevents third-party apps from modifying volumes. If media volume is off, then the alarm is muted. To ensure the alarm rings, users should turn on media volume before setting the alarm. For consistency, we don't add volume checks for Android, maintaining a uniform user experience on both platforms. Feel free to add one in your app is desired.

Let me know if you have a comment or any other question.

**Comment by dtkdt100** [comment]
@gdelataillade I think in order to achive this behavoir, alarm apps in iOS are turning up the volume and then turring it down again. (https://pub.dev/packages/perfect_volume_control)

Furthermore, you could use these parmas to stop and replay any other music that the iphone user:

```dart
avAudioSessionCategory: AVAudioSessionCategory.playback,
avAudioSessionCategoryOptions: AVAudioSessionCategoryOptions.none,
```

in the audio_session package^.

Maybe you could to the same behavoir with that?

**Comment by gdelataillade** [comment]
I think the `perfect_volume_control` changes the volume relatively to the device volume set by the user. I mean if the device volume is 70% and I set it to 1.0, then my audio will player with volume 70%. If I set it to 0.5, then it will play with 35%.

Good point for the `audio_session` feature thanks.

**Comment by dtkdt100** [comment]
hmm, intersting. Is there any other volume package that will change the app volume not relativly? I mean there has to be something right? how does the native alarm is working in iOS?

https://pub.dev/packages/volume_control
https://pub.dev/packages/lecle_volume_flutter

**Comment by gdelataillade** [comment]
I just tested the app Alarmy and what they do is that they set the media volume to the maximum at the moment the alarm starts ringing, and then they put it back like it was before.

So yes there's a way to do it !

**Comment by gdelataillade** [comment]
@dtkdt100  This feature will require some research and refactoring. Honestly I don't have a lot of time at the moment, so feel free to contribute if you want. Otherwise, I'll do it but I can't tell you right now when it will be done.

**Comment by gdelataillade** [comment]
This feature was released in the latest version !

**Comment by dtkdt100** [comment]
@gdelataillade Thank you very much!
