### ISSUE TITLE
Cannot run alarm when app is in background

### ISSUE THREAD

**Issue by Tyluuus** [gdelataillade/alarm#38]
**Alarm plugin version**
1.0.0

**Describe the bug**
I'm using firebase messaging and put code for calling an alarm in backgroud handler but when notification is received and app is trying to start alarm there is exception thrown.

E/MethodChannel#dexterous.com/flutter/local_notifications(22861): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at androidx.core.app.NotificationManagerCompat.<init>(NotificationManagerCompat.java:164)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at androidx.core.app.NotificationManagerCompat.from(NotificationManagerCompat.java:159)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.requestPermission(FlutterLocalNotificationsPlugin.java:1665)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1308)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at android.os.Looper.loop(Looper.java:246)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#dexterous.com/flutter/local_notifications(22861): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/AlarmService(22861): AlarmService started!

**To Reproduce**
*Steps to reproduce the behavior:*
1. Initialize firebase messaging
2. Add to firebase background handler setting alarm to call in moment of receive
3. Send test message from firebase messaging console

**Expected behavior**

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
Samsung Galaxy A50, Android 11

**Additional context**
*Add any other context about the problem here.*

**Comment by gdelataillade** [comment]
Hi @Tyluuus 

It looks like the `flutter_local_notification` dependency was not initialized. Have you followed the [installation steps](https://github.com/gdelataillade/alarm#android-installation-steps) in the README ? 
If so, have you put this line in your `main` function before `runApp`:
`WidgetsFlutterBinding.ensureInitialized();` ?

**Comment by Tyluuus** [comment]
Hi @gdelataillade,
I've followed installation steps and have that call in main function. Problem occurs probably cause i'm trying to call it in funtion marked as @pragma('vm:entry-point')

**Comment by Tyluuus** [comment]
Ok, I succeeded in locating problem. Problem was indeed with local notifications - in requesting for permission to show notification on kill. When i created Alarm settings and set `enableNotificationOnKill: false,` alarm is starting correctly.
