### ISSUE TITLE
App doesn't working without "Audio, AirPlay, and Picture in Picture"

### ISSUE THREAD

**Issue by yaronwalterheylife** [gdelataillade/alarm#40]
**Alarm plugin version**
1.0.2

**Describe the bug**
We develop an app that can't use music permissions

**To Reproduce**
*Steps to reproduce the behavior:*
Run the example

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Comment by gdelataillade** [comment]
What is the purpose of your app ?
What error do you get ?

**Comment by yaronwalterheylife** [comment]
We develop digital planner / calendar app
There is no error code in the log
We can see this
2023-04-16 14:11:34.099805+0300 Runner[3908:1363351] flutter: [Alarm] Notification with id 94048 scheduled successfuly at 2023-04-16 11:13:00.000Z
2023-04-16 14:11:34.488450+0300 Runner[3908:1363351] flutter: [Alarm] Alarm with id 94048 scheduled successfully at 2023-04-16 14:13:00.000
And when the time arrive we see only Local notification
"Alarm example"
"Your alarm (94048) is ringing"

**Comment by gdelataillade** [comment]
Your issue is that you expect the audio to play but it's not playing ?

**Comment by yaronwalterheylife** [comment]
Yes
btw , we want to ask you something about your code 
Yaron.walter@heylife.app

**Comment by gdelataillade** [comment]
Sure. You can ask here too.
