### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by whenyourapprun** [gdelataillade/alarm#44]
**Alarm plugin version**
1.0.3

**Describe the bug**
BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

* What went wrong:
Could not determine the dependencies of task ':flutter_fgbg:compileDebugAidl'.
> javax.xml.bind.UnmarshalException (no error message)

**Comment by gdelataillade** [comment]
Hi @whenyourapprun 

It looks like the issue is related to the `flutter_fgbg` dependency. You can probably fix this issue by running:
```
flutter clean
flutter pub get
flutter run
```

Let me know if it still doesn't work after that.

**Comment by whenyourapprun** [comment]
I ran the command as instructed, but got the same result.
Are there any other settings or changes?

**Comment by gdelataillade** [comment]
Hi @whenyourapprun,

Sorry for the huge delay. Please let me know if you were you able to solve your issue.
