### ISSUE TITLE
Incompatible with 14.0.0+1 version of flutter_local_notifications

### ISSUE THREAD

**Issue by khoafornia** [gdelataillade/alarm#46]
**Alarm plugin version**
1.0.4
**Describe the bug**
Tried to add package with the latest flutter_local_notifications package and got this error:
`Because every version of alarm depends on flutter_local_notifications ^13.0.0 and app_name depends on flutter_local_notifications ^14.0.0+1, alarm is forbidden.`

**To Reproduce**
*Steps to reproduce the behavior:*
1. Run `flutter pub add flutter_local_notifications` then `flutter pub add alarm`

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: iPhone 13 Pro, iOS 16.2, ...*

**Additional context**
*Add any other context about the problem here.*

**Comment by gdelataillade** [comment]
@khoafornia thanks for your interest in the package.

Yes, the package `flutter_local_notifications` has been recently updated to `14.0.0`. I'll update it as soon as possible in the plugin !

**Comment by gdelataillade** [comment]
@khoafornia your issue should be fixed now, please update `alarm` to `1.0.5` and let me know if it works as expected.

**Comment by khoafornia** [comment]
You're too fast @gdelataillade! 🙌 I'll give it a try!
