### ISSUE TITLE
The network URL not working.

### ISSUE THREAD

**Issue by dev-chetan** [gdelataillade/alarm#48]
The network URL not working.

LIKE THIS :
final alarmSettings = AlarmSettings(
        id: alarmId,
        dateTime: dateTime,
        assetAudioPath:
            'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
        loopAudio: true,
        fadeDuration: 3.0,
        notificationTitle: 'Alarm is ringing.',
        //enableNotificationOnKill: false,
        vibrate: true);
        
GET ERROR : Error: PlatformException(NATIVE_ERR, [Alarm] Error with audio file: path is SoundHelix-Song-1.mp3, null, null)

**Comment by gdelataillade** [comment]
Thanks for your interest in the package.

I'll fix this as soon as possible.

**Comment by dev-chetan** [comment]
@gdelataillade if not internet connect then play the default sound.

**Comment by gdelataillade** [comment]
Hello @dev-chetan,

Thank you for your feedback, and I appreciate your patience while I've been addressing this issue.

Upon investigation, it appears that the iOS AVAudioPlayer is unable to directly stream and play audio from a URL. The process currently requires the audio file to be downloaded first and then played, which could potentially cause delays especially if the audio file is quite large. This delay might not be ideal if the alarm needs to trigger instantly.

Regarding the suggestion for the plugin to play a default sound when the device is not connected to the internet, it's important to note that it would necessitate storing an asset within the plugin. This isn't typically best practice, as it could lead to unnecessary bloating of the plugin. Instead, a more feasible solution might be to throw an exception when the device isn't connected to the internet. This would allow you to catch the exception in your own code and manage how to handle it, such as playing a default sound on your side.

I hope this suggestion aligns with your requirements, and I'm open to further discussions to ensure that we provide the best possible user experience.

Looking forward to hearing your thoughts on this.

**Comment by dev-chetan** [comment]
@gdelataillade thanks for replay,

if I provide a downloaded audio local path, will you play an alarm sound?

**Comment by dev-chetan** [comment]
@gdelataillade any update?

**Comment by gdelataillade** [comment]
Hey @dev-chetan,

I'm currently on vacation, I won't be able to finish this very soon but I'll keep you updated.

**Comment by dev-chetan** [comment]
Okay, thanks for the reply,
I will check.

**Comment by EArminjon** [comment]
> Hi @dev-chetan,
> 
> So sorry for the long delay.
> 
> I had too many issues with the network URL support so I removed it and replace it with a downloaded audio local path support, like you suggested. This way, the alarm plugin does not have to manage downloads, which is I think more appropriate.
> 
> Please upgrade the plugin to `1.1.0` and let me know if it works as excepted.

Sorry to up this topic. In case of 'web radio', i would like to create an alarm which wake up my user with the web radio flux url. It is very nice feature, do you plan it or too complex ?

**Comment by gdelataillade** [comment]
Hi @EArminjon,

Thanks for your interest and suggestion for the plugin.

Implementing web radio functionality is indeed possible, but I must admit it won't be a priority at the moment. I'm mostly working alone on this project in my spare time.
