### ISSUE TITLE
Not working on the firebase messaging background handler

### ISSUE THREAD

**Issue by FullStack1106** [gdelataillade/alarm#50]
```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  RemoteNotification? notification = message.notification;
  String? newTitle = notification?.title;
  print("Notification Title ${notification?.title}");
  if(notification?.title == "Session Expired"){
    ///custom handler
  }
  String messageCategory = message.data['category'].toString();
  if(messageCategory == "cash_request"){
    final alarmSettings = AlarmSettings(
      id: 42,
      dateTime: DateTime.now(),
      assetAudioPath: 'assets/nokia.mp3',
      loopAudio: true,
      vibrate: true,
      fadeDuration: 3.0,
      notificationTitle: 'This is the title',
      notificationBody: 'This is the body',
      enableNotificationOnKill: false,
    );
    await Alarm.set( alarmSettings: alarmSettings);
  }
}
```
Please check this code.
I am going to alarm when I receive specific push notficiation, but does not work.
When app is open and when I try to ring on the home.dart file, it works.
But when I try to ring on the firebase messaging background handler of main.dart file, does not work.
I followed this [issue](https://github.com/gdelataillade/alarm/issues/38), but does not work on my side.
Thank you.

**Comment by gdelataillade** [comment]
Hello @FullStack1106,

This is what the [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/flutter/receive#apple_platforms_and_android) says:

> There are a few things to keep in mind about your background message handler:
>
> 1) It must not be an anonymous function.
> 2) It must be a top-level function (e.g. not a class method which requires initialization).
> 3) When using Flutter version 3.3.0 or higher, the message handler must be annotated with `@pragma('vm:entry-point')` right above the function declaration (otherwise it may be removed during tree shaking for release mode).

Let me know if it doesn't help and I'll take more time to analyze your issue.
