### ISSUE TITLE
Alarm settings

### ISSUE THREAD

**Issue by sandamil** [gdelataillade/alarm#51]
Would it be possible to use the alarm edition to change the settings of all the alarms and not just the one you are creating?

**Comment by gdelataillade** [comment]
Hey @sandamil,

You could just call `Alarm.getAlarms()` to retrieve all the active alarms.
Then, loop on the alarms and call `Alarm.set` with the your new settings to override them.
You can use the method `copyWith` on the `AlarmSettings` model to easily change a specific property.

Let me know if you have any other question.
