### ISSUE TITLE
The IOS alarm app does not ring when the app is on the background for long duration

### ISSUE THREAD

**Issue by moosalim** [gdelataillade/alarm#53]
**Alarm plugin version**
1.0.5

**Describe the bug**
On ios, the alarm does not work after when the app is on the background for long duration say about 10 hours and sometimes less than this. It seems the app goes to sleep mode and therefore, it will not ring. When I tried to bring the app from background to foreground, it starts fresh again as if it was closed and reopened. I thought there is an issue with the configuration of my app, but I have tested the example app provided along with this package, and I found that the example app has the same issue as well.

**Comment by gdelataillade** [comment]
Hi @moosalim,

Sorry to hear about your issue. As iOS and Android often terminates background applications when allocating resources, especially in low power mode, this could be causing your problem. However, it's unusual as the alarm process shouldn't require significant resources.

Could you provide details about your device? This will help me diagnose and address the issue effectively. Thanks in advance.

**Comment by moosalim** [comment]
Hi @gdelataillade , thanks for your reply. my device is iPhone x , iOS version: 16.3.1 

I think some property needs to be added to the ios code to prevent the app from going sleep, see this:

https://developermemos.com/posts/prevent-device-sleep-swift
https://stackoverflow.com/questions/54002649/ios-swift-uiapplication-shared-isidletimerdisabled-true-not-working-after-revi

**Comment by gdelataillade** [comment]
Hi @moosalim,

It looks like the `isIdleTimerDisabled` property is to prevent the device to sleep. It means that the screen will stay on as long as the app is open, like when you are playing a video.

The issue is that the battery will drain much faster if the screen stays on. What do you think ?

**Comment by moosalim** [comment]
Hi @gdelataillade 
Agree, the `isIdleTimerDisabled ` might not be the solution. I thought I will just provide you with some links about the topic.

What do you think the solution. I am sure there is something that could force the app to continue working while it is on the background. for example `Alarmy` app does that.

**Comment by gdelataillade** [comment]
Hi @moosalim,

I took a deep look at Alarmy app and I found a FAQ section in the Settings tab. One of the topic is: "My alarm didn't ring", and they explain the same things I explained earlier... Even Alarmy alarms and not 100% reliable.

Sources:
https://alarmy-ios.zendesk.com/hc/en-us/articles/360004399873--No-ring-My-alarm-didn-t-ring

![IMG_2072](https://github.com/gdelataillade/alarm/assets/32983806/b1e65519-26d6-4643-a6ea-4f97330acb7d)

**Comment by moosalim** [comment]
thanks. I will close this issue then
