### ISSUE TITLE
Alarm doesn't show icon.

### ISSUE THREAD

**Issue by alireza-hnzpv** [gdelataillade/alarm#54]
**Alarm plugin version**
alarm: ^1.0.5

**Describe the bug**
when alarm is ringing, notification doesn't show icon.

I think it is better if the alarm shows only one event. Maybe someone doesn't want to show a notification at the desired time, Or want to personalize the notification.

**Comment by gdelataillade** [comment]
Hi @alireza-hnzpv,

The notification icon doesn't show on iOS or Android ?

Then, I'm not sure to understand what you suggest. You want to be able to customize the alarm notification ?

**Comment by alireza-hnzpv** [comment]
![image](https://github.com/gdelataillade/alarm/assets/103641808/87a1bee7-4d8e-4b76-b46a-3ac08b1c8df3)
![image](https://github.com/gdelataillade/alarm/assets/103641808/a7af355d-be36-47ca-83e9-8c4796404936)

You can see that it does not display an icon.

I mean, instead of the goal being to show a notification for an alarm, it calls an event like callBack. For example, I might want to do another action instead of notification.

**Comment by gdelataillade** [comment]
Hi @alireza-hnzpv 

Do you still have the issue ?

**Comment by gdelataillade** [comment]
Hi @alireza-hnzpv

I just release version `3.0.6` with a fix for your issue.

Please let me know if it works.

**Comment by juanlabrador** [comment]
No, the same problem

**Comment by gdelataillade** [comment]
Hi @juanlabrador 

Thanks for your interest in the package.

Could you provide a screenshot of your notification ? Also, what version of Android are you using ? It could help me identify what's the issue.

**Comment by juanlabrador** [comment]
Hi @gdelataillade 

![Screenshot_2024-01-29-20-40-17-167_com miui home](https://github.com/gdelataillade/alarm/assets/6761048/3abb4d18-6984-49a5-bd26-a8f39e4ad6b6)
![Screenshot_2024-01-29-20-40-06-313_com miui home](https://github.com/gdelataillade/alarm/assets/6761048/be758325-9fc3-45b6-b8bc-d488bdca2f61)

**Comment by gdelataillade** [comment]
Hi @juanlabrador 

I just released version `3.1.1` with a fix for the notification icon. Please let me know if it works for you.
