### ISSUE TITLE
Schedule Alarm gives all notification at once. If i schedule it for 30 days at 11:30 i get all 30 days  triggers at  once

### ISSUE THREAD

**Issue by madhusudhan1557** [gdelataillade/alarm#60]
for (var i = 0; i < 30; i++) {
                  print(alarmDateTime.add(Duration(days: i)));
                  final AlarmSettings alarmSettings = await AlarmSettings(
                    id: alarmId + i,
                    dateTime: alarmDateTime.add(Duration(days: i)),
                    assetAudioPath: "assets/alarm.mp3",
                    notificationTitle: "Alarm Reminder",
                    notificationBody: "Please Take Your $drugName",
                    vibrate: true,
                    enableNotificationOnKill: true,
                  );
                  await Alarm.set(alarmSettings: alarmSettings);
                }
 ______________________________________________________________________________________________________
 I/flutter (14683): [Alarm] Notification with id 1139753 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-15 11:56:00.000
I/flutter (14683): [Alarm] Notification with id 1139754 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-16 11:56:00.000
I/flutter (14683): [Alarm] Notification with id 1139755 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-17 11:56:00.000
I/flutter (14683): [Alarm] Notification with id 1139756 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-18 11:56:00.000
I/flutter (14683): [Alarm] Notification with id 1139757 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-19 11:56:00.000
I/flutter (14683): [Alarm] Notification with id 1139758 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-20 11:56:00.000
I/flutter (14683): [Alarm] Notification with id 1139759 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-21 11:56:00.000
I/flutter (14683): [Alarm] Notification with id 1139760 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-22 11:56:00.000
I/flutter (14683): [Alarm] Notification with id 1139761 scheduled successfuly at 2023-06-30 06:11:00.000Z
I/flutter (14683): 2023-07-23 11:56:00.000
________________________________________________________________________________________________________
this is what my console looks like
![Screenshot_2023-06-30-11-58-08-07_cc21deb282a7fadf0aa010e637f06a84](https://github.com/gdelataillade/alarm/assets/100462733/b1c40ae5-b7d4-4bc2-ab93-26a9abf3b684)

**Comment by gdelataillade** [comment]
Hi @madhusudhan1557,

I fixed an issue that looks very similar last week. Are you using the last version on the plugin ?
