### ISSUE TITLE
Every time I set an alarm, it warns me today

### ISSUE THREAD

**Issue by alireza-hnzpv** [gdelataillade/alarm#61]
**Alarm plugin version**
^1.0.5

**Describe the bug**
i set alaram for 2023-07-14 12:00:00 bit it's But he gave an alarm for today (2023-07-09  12:00:00)
Every time I set an alarm, it warns me today

**Comment by gdelataillade** [comment]
Hi @alireza-hnzpv,

Thanks for your interest in the package.

I fixed this issue a few weeks ago. Updating the package should fix your problem.

Let me know if it works as expected.
