### ISSUE TITLE
show notification about 'your alarms may not ring'

### ISSUE THREAD

**Issue by alireza-hnzpv** [gdelataillade/alarm#63]
**Alarm plugin version**
^1.1.5

**Describe the bug**
![photo_2023-07-13_11-28-51](https://github.com/gdelataillade/alarm/assets/103641808/e4b08d71-6a93-4b35-adb3-9d3a78793d94)

My users who have Android 11 sent me this photo. Getting annoyed by this notification. Users declare that by closing the app, this message will be displayed to them immediately and they are upset about this. How can I disable this notification? There are other apps that work properly on Android 11 without any problems.

**Comment by gdelataillade** [comment]
Hi @alireza-hnzpv,

To disable this notification when the app is killed, just set the parameter `enableNotificationOnKill` to `false`.

**Comment by alireza-hnzpv** [comment]
thank you :-)
