### ISSUE TITLE
Not playing in background or lock screen for IOS

### ISSUE THREAD

**Issue by TotallyScience** [gdelataillade/alarm#67]
I am using version 1.1.5.

I have been working to implement your alarm package with a Flutter app of mine for the past few days. I am having issues with the alarm playing sound or vibrating in the background or the lock screen of my ios phone. It is an iPhone 13, using IOS 16.2.

I have tried it in "Debug" mode and "Release" mode. In Debug mode, the vibration works in the background but not the sound. In Release mode, neither works. 

In the simulation of an iPhone 14, the sound does play in the background and on the lock screen. I am unsure about the vibrations because it is a simulation.

Any advice?

**Comment by gdelataillade** [comment]
Hi @TotallyScience,

Thanks for your interest in the plugin.

I'm sorry to hear that you encounter these issues. Please answer the following questions, they might help me identify the problem:

1) Do you receive the notification ?
2) Is your device is Do not Disturb mode or Sleep mode ?
3) In your tests, how long did you have to wait to receive the vibrations ?

Best regards

**Comment by TotallyScience** [comment]
I did get the notification, yes. I tried in Do not Disturb mode, Sleep mode, and with nothing on. In my tests, I waited would wait up to a minute but nothing would happen until I opened the app. I left it in the background and never killed it.

I downloaded and tested the example code posted on your GitHub and that actually worked, so I think it must be something I did differently in implementation.

My code is very simple, as I just have the alarm play 5 seconds after opening the app. I basically just took the tutorial code you posted on the package. 

This is my code:

Future<void> main() async {
  runApp(MultiProvider(providers: [
    ChangeNotifierProvider(create: (_) => SoundsModel()..initialize()),
    ChangeNotifierProvider(create: (_) => PageModel(Page.home)),
    ChangeNotifierProvider(create: (_) => PreviewAudioPlayerModel())
  ], child: const GrindClock()));

  await Alarm.init();

  DateTime now = DateTime.now();
  DateTime thirtySecondsFromNow = now.add(const Duration(seconds: 5));

  final alarmSettings = AlarmSettings(
    id: 42,
    dateTime: thirtySecondsFromNow,
    assetAudioPath: 'assets/tes.mp3',
    loopAudio: true,
    vibrate: true,
    fadeDuration: 3.0,
    notificationTitle: 'This is the title',
    notificationBody: 'This is the body',
    enableNotificationOnKill: true,
  );
  await Alarm.set(alarmSettings: alarmSettings);
}

**Comment by gdelataillade** [comment]
Hi @TotallyScience,

Thanks for the details.

Just to be sure, did you follow the [iOS installation step in the README](https://pub.dev/packages/alarm#ios-installation-stepshttps://pub.dev/packages/alarm#ios-installation-steps) in the 'Getting Started' section ?

**Comment by TotallyScience** [comment]
Setting the correct background mode in Xcode fixed it. Thank you so much!
