### ISSUE TITLE
Ability to create repeating/periodic alarms

### ISSUE THREAD

**Issue by GraSim** [gdelataillade/alarm#69]
Feature request for the ability to set repetitive alarms e.g everyday at the same time or every Monday etc

**Comment by gdelataillade** [comment]
Hi @GraSim,

Thanks for your interest in the package.

For now, there is no reliable solution in iOS to schedule periodic alarms. I'll take a deep look at it as soon as I find the time, but it looks like it's not possible. At the moment, the best way to manage periodical alarms for you would be to schedule manually your alarms for the following week and every time the user opens the app, run a function that will verify and schedule the next alarms.

Duplicate: #47

**Comment by GraSim** [comment]
Hi @gdelataillade Thanks for the response, I have also read #47 and I will consider what approach to that. But for future consideration, is this something the plugin could handle under the hood? So "mimic" periodic ability by either rescheduling for the week or recreating each alarm? Just a thought for future enhancement.

**Comment by gdelataillade** [comment]
Hi @GraSim 

I have to think about it because I want the package to be suitable for every use, and everyone has a different use...
