### ISSUE TITLE
App Crashes upon scheduling an alarm

### ISSUE THREAD

**Issue by SamuelBehrmann** [gdelataillade/alarm#71]
**Alarm plugin version**
1.1.7

I schedule 2 alarms, the first one to go off instantly and another one after some duration of time. After a fresh install of the app (in debug or release mode doesnt matter) the first time i try to schedule an alarm the app freezes and or just closes. Also this is appearing when permission have been granted and if they haven't been granted.

**To Reproduce**

1. Initialize the package
2. Schedule an alarm
3. App crashes.

**Expected behavior**
The App should not crash. 

**Screenshots**
![image](https://github.com/gdelataillade/alarm/assets/79116396/dfb44bcb-144e-4a4c-a6df-369f689222fd)

The Error Message i get:
``` 
* thread #3, queue = 'com.apple.root.default-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0x8000000000000028)
    frame #0: 0x00000001b855b6c0 libswiftCore.dylib`Swift.__RawDictionaryStorage.find<τ_0_0 where τ_0_0: Swift.Hashable>(τ_0_0) -> (bucket: Swift._HashTable.Bucket, found: Swift.Bool) + 36
libswiftCore.dylib`Swift.__RawDictionaryStorage.find<τ_0_0 where τ_0_0: Swift.Hashable>(τ_0_0) -> (bucket: Swift._HashTable.Bucket, found: Swift.Bool):
->  0x1b855b6c0 <+36>: ldr    x0, [x19, #0x28]
    0x1b855b6c4 <+40>: mov    x8, x2
    0x1b855b6c8 <+44>: ldr    x9, [x8, #0x20]!
    0x1b855b6cc <+48>: mov    x17, x8
Target 0: (Runner) stopped.
Error launching application on iPhone von Samuel (3).
Exited
```

**Device info**
iPhone 12, iOS 16.4

**Additional context**

**Comment by gdelataillade** [comment]
Hey @aissam-amez,

Sorry to hear you have this issue too.

Can you both provide detailed steps to reproduce the issue ? I'm not able to reproduce it on my device. Also provide the frequency of the crash.

Thanks in advance

**Comment by aissam-amez** [comment]
I have a fitness app that allows users to select how much time for training and adjust it in multiple sets
for each set it will have an alarm to notify that the set is finished.
here is my code: 

`for (var i = 1; i <= countTimes; i++) {
      final alarmSettings = AlarmSettings(
        id: i,
        dateTime: DateTime.fromMillisecondsSinceEpoch(
            timeNow + i * 20 * minuteInMilliseconds),
        assetAudioPath: 'assets/songs/alarm.mp3',
        fadeDuration: 3.0,
        notificationTitle: 'fitness app',
        notificationBody:
            '$separateTime minutes has passed. it is time for the other set',
        enableNotificationOnKill: false,
      );
      Alarm.set(alarmSettings: alarmSettings);
      setState(() {});
    }
  }`

the odd thing is that the app sometimes works fine, and sometime the app crashes when set the alarms  like 5% of the time

**Comment by gdelataillade** [comment]
OK thank you for your answer, I'll look into it as soon as possible.

**Comment by imperialmarch55** [comment]
Sending notifications causes the app to crash on Android 7.1.1, and probably other older versions too.  Everything else works fine for me so far if I'm not using notifications.

**Comment by gdelataillade** [comment]
Hi @imperialmarch55 

Please make sure you followed the installation steps. Otherwise, do you have any logs before your app crashes ? Could be very useful to identify your issue.

**Comment by synstin** [comment]
I'm experiencing the same thing.
The app crashes when I try to register multiple alarms.

```
Exception: Unable to terminate com.xxx on B940F6DF-F90D-4633-A8A4-7B35C85E011A:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
found nothing to terminate
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	The request to terminate "com.xxx" failed. found nothing to terminate
	found nothing to terminate
  Command: /usr/bin/arch -arm64e xcrun simctl terminate B940F6DF-F90D-4633-A8A4-7B35C85E011A com.xxx
the Dart compiler exited unexpectedly.
```

**Comment by gdelataillade** [comment]
Hi @synstin 

It might be a Simulator issue. Do you have a physical iOS device to test ?

**Comment by synstin** [comment]
@gdelataillade 
I thought it was a simulator issue too, but I'm currently testing in testflight.

It happens less in testflight than in the simulator, but it does happen.

I am using an iPhone 14.

**Comment by gdelataillade** [comment]
Hi @synstin 

Thanks for your answer.

I think you should try to wait for an alarm to be set before trying to set another one, with `await` keyword:

```Dart
for (final alarm in alarmList) {
   await set(alarmSettings: alarm);
}
```

The issue occurs maybe because of concurrency. Let me know if it fixes your issue.

**Comment by synstin** [comment]
@gdelataillade It's fixed perfectly, thank you.
