### ISSUE TITLE
Alarm.isRinging forgot to add OS check and missing android function

### ISSUE THREAD

**Issue by whowillcare** [gdelataillade/alarm#73]
**Alarm plugin version**
*version 1.1.7*

**Describe the bug**
*function in alarm.dart, line: 164, it only checks IOSAlarm*

**To Reproduce**
1. run checking isRinging in any aroid

**Comment by gdelataillade** [comment]
Hi @whowillcare,

Thanks for opening this issue. I'll add the android check as soon as possible and I'll keep you updated !

**Comment by gdelataillade** [comment]
Hi @whowillcare,

I added the method for Android and updated the plugin to `1.1.8`.

Please update the plugin in your project and let me know if it works as expected.

**Comment by whowillcare** [comment]
It does seem to work now. However, the newest version has introduced new bug.

**Comment by whowillcare** [comment]
With deeper test,  and I found even when Alarm was really ringing, the return was still false somehow for android, iOS was fine. thanks

**Comment by gdelataillade** [comment]
I was not able to reproduce this issue.

What is your use case for the `isRinging` method ? Have you consider using `ringStream` ? I was thinking deprecating `isRinging `, what do you think ?
