### ISSUE TITLE
Use iOS critical alarm feature

### ISSUE THREAD

**Issue by ondanplatform** [gdelataillade/alarm#76]
critical alarm might be alternative of notification. for testing take a look at Midnight(alarm app in app store(ios). 

https://blog.kulman.sk/using-critical-alerts-on-ios/
https://developer.apple.com/documentation/usernotifications/unauthorizationoptions/2963120-criticalalert

I don't know there is something like that in android or not.

**Comment by gdelataillade** [comment]
Hello @ondanplatform,

Thank you for your suggestion.

About the critical alerts idea:

- Getting permission from Apple for this is not easy. My plugin doesn't have it, but app makers can try to add it themselves.
- I'm not sure if Apple would say OK to every app using my plugin for this. Big apps like Alarmy don't even use it.
- If you use the volumeMax setting in my plugin and the app is still open, the alarm should be loud and clear.

What do you think?

**Comment by ondanplatform** [comment]
@gdelataillade No problem for me, I just saw Midnight alaram app and it's use this critical alarm functionality. I wanted suggest to you
