### ISSUE TITLE
Download audio not set check error.

### ISSUE THREAD

**Issue by dev-chetan** [gdelataillade/alarm#77]
Error: PlatformException(NATIVE_ERR, [Alarm] Error loading given local asset path: /Users/dev/Library/Developer/CoreSimulator/Devices/773208AB-83CA-48B4-9150-DE7D46ADB1FC/data/Containers/Data/Application/7F4FBE5A-AD72-4068-8CC0-401BE25475A4/Documents/audio/5e06342ad00acb4894a3a919.mp3, null, null)

Not Working download the audio play please check.

**Comment by gdelataillade** [comment]
Hi @dev-chetan,

Thanks for opening the issue.

Could you try with a real device ? Not simulator.

**Comment by dev-chetan** [comment]
I use a simulator.

**Comment by dev-chetan** [comment]
Hello, 
Not working in real device

flutter: │ 🐛 Error: PlatformException(NATIVE_ERR, [Alarm] Error loading given local asset path: /var/mobile/Containers/Data/Application/56DCFF1D-DE87-4C71-B968-A9630C53CC98/Documents/audio/1646725181394_photo-1646725181348.mp3, null, nul

**Comment by dev-chetan** [comment]
@gdelataillade 

please set new param like a "customPath" 


DOCUMENT PATH : /var/mobile/Containers/Data/Application/56DCFF1D-DE87-4C71-B968-A9630C53CC98/Documents
Extra Path : audio

let assetAudioURL = documentsDirectory.appendingPathComponent( extraPath.isEmpty? filename : "(extraPath)/\(filename)")
 
if you set "extraPath" param, 
this is a permanent solution

Above solution is worked

**Comment by gdelataillade** [comment]
Hi @dev-chetan 

Thanks for the suggestion. I'll fix this as soon as possible and I'll let you know.

**Comment by dev-chetan** [comment]
Working fine but add extraPath

**Comment by dev-chetan** [comment]
Working fine but add extraPath.

**Comment by gdelataillade** [comment]
Hi @dev-chetan 

I see you closed the issue. Did you find a way to fix your problem ?
