### ISSUE TITLE
No sound when screen is locked on iOS

### ISSUE THREAD

**Issue by andriisemenov-emma** [gdelataillade/alarm#8]
Hi! Unfortunately, the there is no sound when the alarm rings when screen is locked. I can see the notification pop up, but the sound did not ring. Below is the sample output when I set an alarm 30 seconds from current time. The alarm rings only when I unlock the screen. Same happens if the app is not in the foreground. 

iPhone 13 Pro
iOS: 16.2

`2023-01-23 20:48:34.080940+0100 Runner[1290:266664] flutter: [Alarm] Notification scheduled successfuly at 2023-01-23 19:49:00.000Z
2023-01-23 20:48:34.135589+0100 Runner[1290:266664] flutter: [Alarm] alarm set successfully
2023-01-23 20:48:38.744712+0100 Runner[1290:266664] flutter: [Alarm] onAppStateChange FGBGType.background
2023-01-23 20:49:27.326862+0100 Runner[1290:266664] flutter: [Alarm] onAppStateChange FGBGType.foreground
2023-01-23 20:49:27.331791+0100 Runner[1290:266664] flutter: [Alarm] onRing
2023-01-23 20:49:27.331915+0100 Runner[1290:266664] flutter: onRing
2023-01-23 20:49:28.005879+0100 Runner[1290:266664] flutter: [Alarm] alarm is ringing: true
2023-01-23 20:49:28.006017+0100 Runner[1290:266664] flutter: onRing
2023-01-23 20:49:29.726962+0100 Runner[1290:266664] flutter: [Alarm] onAppStateChange FGBGType.background`

Flutter doctor output:
`[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-DE)
    • Flutter version 3.3.10 on channel stable at /Users/andriisemenov/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • Andrii’s iPhone (mobile) • 00008110-001034EA0C86401E • ios            • iOS 16.2 20C65
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.`

**Comment by yelkamel** [comment]
Thank you for your interest in the package.

Sorry for the late answer.

Do you still have the issue? My teammate and I don’t experience it and are unable to reproduce it. The error seems to be related to the audio session playback.

By any chance, do you wrote Swift code in your project ? It may interfere with the package’s code.
If not, could you please try to replicate your issue in an empty project and let us know ?

Best regards,
Youcef

**Comment by andriisemenov-emma** [comment]
Hi, got my hands again on it and retested with a fresh flutter project:

Phone 13 Pro
iOS: 16.2

`import 'package:flutter/material.dart';
import 'package:alarm/alarm.dart';

// void main() {
//   runApp(const MyApp());
// }

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  await Alarm.init(showDebugLogs: true);

  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  AlarmSettings alarmSettings() {
    return AlarmSettings(
      id: 42,
      dateTime: DateTime.fromMillisecondsSinceEpoch(
          DateTime.now().millisecondsSinceEpoch + 10000),
      assetAudioPath: 'assets/alarm.mp3',
      loopAudio: true,
      vibrate: true,
      fadeDuration: 3.0,
      notificationTitle: 'This is the title',
      notificationBody: 'This is the body',
      enableNotificationOnKill: true,
    );
  }

  Future<void> _incrementCounter() async {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
    await Alarm.set(alarmSettings: alarmSettings());
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

pubspec:

`name: sound_alarm_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  alarm: ^0.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

error when screen locked or app exited ( not killed ):
`flutter: [Alarm] Notification with id 42 scheduled successfuly at 2023-04-05 14:41:40.000Z
flutter: [Alarm] Alarm with id 42 scheduled successfully at 2023-04-05 16:41:40.799
2
[as] ATAudioSessionClientImpl.mm:274   activation failed. status = 561015905`

**Comment by gdelataillade** [comment]
Sorry I'm not sure to understand what's the issue. The audio is not playing on iOS ?

**Comment by andriisemenov-emma** [comment]
@gdelataillade, that's correct. The audio is not played when the app is exited ( not killed ). And there is no notification, not even vibration, when the screen is locked.

**Comment by gdelataillade** [comment]
Hi @andriisemenov-emma 

Could you provide more information about your device, the version of the plugin and the steps to reproduce your issue please ?

**Comment by samerkh** [comment]
i use ios 16.4, there is no sound to the notification, it shows but without sound or vibration, only when i click on it and it opens the app that the sound starts

**Comment by gdelataillade** [comment]
Do you still have the issue with plugin version `1.0.1` ? Fixes were made for iOS.
If not, tell me if the issue happened in debug or release mode.

**Comment by samerkh** [comment]
what i found is that when app is fully closed on iphone the sound does not work, but when kept in background it works fine

**Comment by gdelataillade** [comment]
@samerkh as explained in the README, when app is killed, all alarms are killed by the device OS. There's nothing to do about it, this is how device OS are designed. I recommend you to take a look at the plugin's notification-on-kill feature though.

**Comment by samerkh** [comment]
but that's not the case with flutter_local_notifications. I can schedule a notification and it will play the sound even when app is killed, also there are some alarm apps on the appstore that also play a sound even when the app is killed.

**Comment by gdelataillade** [comment]
> also there are some alarm apps on the appstore that also play a sound even when the app is killed.

Which ones ?

**Comment by samerkh** [comment]
One called alarmClock and another one called alarmy. Alarmy does notify you when you kill the app that the sound may not fire, but it still does

**Comment by gdelataillade** [comment]
Well to be honest I don't know how they manage to do that. I tried to contact a iOS developer from Alarmy to ask him questions about the feature but I never got any answer.

This is an open-source project so if you have the skills and time feel free to do your own research and contribute to the plugin. It would be greatly appreciated.

**Comment by samerkh** [comment]
okay thanks, I appreciate your help!
