### ISSUE TITLE
Exchange <bool>volumeMax with <double>forcedVolume

### ISSUE THREAD

**Issue by maxx-st** [gdelataillade/alarm#83]
**Is your feature request related to a problem? Please describe.**
While the volumeMax-property is very useful, it's not very satisfying as a customer using the app, because it is extremely loud.
And setting volumeMax to false may comes with the risk of having the volume set at zero and therefore no alarm ringing.

**Describe the solution you'd like**
Change the volumeMax property to a forcedVolume? property, where the programmer can specify a number from 0.0 (silent) to 1.0 (maximum volume). This way, the volume can be forced to e.g. 0.7, which is loud enough to get notified.
Ideally, make the forcedVolume nullable, so when null, the device-volume is used.

**Comment by gdelataillade** [comment]
Hi @maxx-st 

Thanks for your interest in the package.

Yes this would be very useful. I was thinking adding this feature very soon. I'll let you know when it's available.

**Comment by maxx-st** [comment]
Great to hear!

While we are at it: Could you add an additional attribute for showSystemUI, so the volume-controller can be hidden from the user?

**Comment by gdelataillade** [comment]
Hi @maxx-st

Thanks for you feedback. I'm going to start developing these changes now but they might be released later for version `3.0.0` because it will involve breaking changes.

I'll keep you updated in this issue.
