### ISSUE TITLE
Custom alarm id

### ISSUE THREAD

**Issue by stevenosse** [gdelataillade/alarm#9]
Hey
Thank you for this great package !
It would be great if we could define custom id for alarms.

This would open the room for other features like alarms cancelling.

My thoughts :
- `Alarm.set` would take a custom id
- A new `Alarm.cancel` would take an id as param and cancel the desired alarm.
    - This feature is available in android_alarm_manager [as defined here](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/android_alarm_manager_plus/lib/android_alarm_manager_plus.dart#L359)

Thank you!

**Comment by gdelataillade** [comment]
Hello

Thank you for your interest in the package.

We definitely have to add this feature. We have other priorities in work in progress at the moment that will bring big improvements but also breaking changes. But we will work on it as soon as we merge those pull requests.

I'll update this thread to keep your informed of the progress of the feature.
