### ISSUE TITLE
[iOS] How can I see if the onKillNotification works in Debug?

### ISSUE THREAD

**Issue by dtkdt100** [gdelataillade/alarm#92]
Hello again!
I am developing a package called: [notification_when_app_is_killed](https://github.com/dtkdt100/notification_when_app_is_killed), and 
I want to check fi the notification is working in ios.

I am working with your code (of course I will give you credit) and I will love your help.

**Alarm plugin version**
latest
**Describe the bug**
In Debug, when the app is killed there is no onKill notification. Video:
https://drive.google.com/file/d/1BoLUAz_IheNwl_nssPBDwVvkqARQAwP5/view?usp=sharing
**To Reproduce**
*Steps to reproduce the behavior:*
Install the example and set alarm

**Expected behavior**
Should send message

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
iPhone 11, latest iOS

**Comment by dtkdt100** [comment]
Hi, I read all of your articles already, awesome stuff!

I ran it also in release in Android studio and it also didn't work (the video is in release mode). Should it be on test flight? Because in iOS the release mode behaves as debug (you can't open the app without the cable)

**Comment by gdelataillade** [comment]
No, no need to make a TestFlight.

What I usually just do is to run `flutter run --release` in the terminal and once the build is over, I remove the lightening cable and then I'm able to kill the app, see the notification and reopen.

This doesn't work for you ?

**Comment by dtkdt100** [comment]
I only try running release from Android studio. I will try via CLI and let you know.

Thanks you🙏

**Comment by dtkdt100** [comment]
Thank you! It works with this command.

I will let you know when the package is finished.

Thanks again, great work @gdelataillade

**Comment by dtkdt100** [comment]
@gdelataillade https://pub.dev/packages/notification_when_app_is_killed
