### ISSUE TITLE
Guideline 2.5.4 - Performance - Software Requirements

### ISSUE THREAD

**Issue by kmi1002** [gdelataillade/alarm#96]
**Regarding Guideline 2.5.4, background audio is intended for use by apps that provide audible content to the user while in the background, such as music player, music creation, or streaming audio apps, not for sending an alert to users.

To resolve this issue, if your app does not have a feature that requires persistent audio, it would be appropriate to remove the "audio" setting from the UIBackgroundModes key.**

This is why the app review application was rejected.
It was said that sound was needed when the alarm sounded, but it was rejected three times for the same reason.
How to solve this?

**Comment by gdelataillade** [comment]
Hi @kmi1002 

Thanks for your interest in the plugin.

I understand the challenges you’re facing with the app review process. Here’s a strategy you can consider when engaging with Apple:

1.	App Review Appeal: Begin by submitting an appeal to the App Review Board. Clearly articulate your reasons for using the silent audio player and its necessity for the app’s functionality.

2.	Emphasize User Experience: Highlight that the core aim of your app is to provide users with a dependable alarm. Without the silent audio player, alarms might not work reliably, compromising user experience. Ensure they understand that this silent audio doesn’t intrude on the user or impact battery life significantly.

3.	Schedule a Consultation: Consider scheduling a call with an App Store Review consultant. Discussing your use case directly might shed more light on the nuances of your implementation and its importance.

4.	Reference Similar Apps: Point out that apps like Alarmy have implemented similar methods. This could help establish a precedent, although it’s not a guaranteed argument.

Engage with Apple constructively and focus on the best experience for your users. All the best with your discussions!

Hope this works for you!

**Comment by gdelataillade** [comment]
Hey @kmi1002 

Let me know if it worked for you. Otherwise, I'll deeply investigate with you on how you can figure it out.
You're the first developer that gave me feedback on App Store review involving my alarm plugin, so it's very important to find a solution.

**Comment by kmi1002** [comment]
@gdelataillade 

The reply was late because I was on vacation.

As instructed, the issue was passed with detailed notes on “Emphasize User Experience” and “Reference Similar Apps” Additionally, I have attached screenshots and videos.
Your kind help was a huge help to me~

The app review hasn't passed yet due to other issues.

**Comment by iamdamjanmiloshevski** [comment]
Why is this closed? My app is still getting rejected with for the same reason even after providing screenshots, screen recording, referenced the Alarmy app and explained clearly to Apple that it's crucial for the User Experience, they are still rejecting it with the following message:

"However, to be in compliance with guideline 2.5.4, it would still be appropriate to remove the "audio" setting from the UIBackgroundModes key. Please note that alarm alerts can be accomplished using Push/Local Notifications."

@gdelataillade what are you suggesting to do?

**Comment by gdelataillade** [comment]
@iamdamjanmiloshevski, I’m confident you can pass the review process; I know many apps that have successfully been approved with alarm features. However, I understand that it’s not always easy. Here’s a refined approach you can try when responding to Apple:

Explain that your app’s alarm feature requires prolonged ringing and vibration to effectively wake users, which **cannot be achieved solely through local or push notifications** due to their time and duration limitations on iOS. Unlike standard notifications, the alarm needs to sound continuously until the user interacts with it, ensuring they wake up and improving user safety and experience.

Emphasize that the audio setting in the UIBackgroundModes key is therefore **essential** for your app’s core functionality. Without it, the app cannot provide the reliable alarm experience users expect, which could lead to negative outcomes (e.g., missing important events or schedules).

**Comment by iamdamjanmiloshevski** [comment]
> @iamdamjanmiloshevski, I’m confident you can pass the review process; I know many apps that have successfully been approved with alarm features. However, I understand that it’s not always easy. Here’s a refined approach you can try when responding to Apple:
> 
> Explain that your app’s alarm feature requires prolonged ringing and vibration to effectively wake users, which **cannot be achieved solely through local or push notifications** due to their time and duration limitations on iOS. Unlike standard notifications, the alarm needs to sound continuously until the user interacts with it, ensuring they wake up and improving user safety and experience.
> 
> Emphasize that the audio setting in the UIBackgroundModes key is therefore **essential** for your app’s core functionality. Without it, the app cannot provide the reliable alarm experience users expect, which could lead to negative outcomes (e.g., missing important events or schedules).

Ok, I will send an appeal now again, last try. 
Btw, I spoke with a fellow iOS developer of mine, he said to submit a new build without any change and submit it for review again and a different reviewer will pick it up, it's how Apple works, he also emphasised to highlight in the testing notes how they can access the background audio. 

I'll send an update here if app review passes or gets rejected again :).

**Comment by gdelataillade** [comment]
OK ! I wish you good luck !

**Comment by iamdamjanmiloshevski** [comment]
No luck with Apple again! Rejected! 

Here is the message:

```
Regarding 2.5.4, we are still unable to locate any features that require persistent audio.
Background audio is intended for use by apps that provide audible content to the user while in the background, such as music player, music creation, or streaming audio apps. 

If the app does not have a feature that requires persistent audio, it would be appropriate to remove the "audio" setting from the UIBackgroundModes key.

We look forward to reviewing your resubmitted app.
```

I've submitted  another build without any changes as advised from my friend who is an experienced iOS dev with a lot experience in App Store. 

If rejected again and not approved Apple  by November 1, 2024, I'll advice the team that we'll removing the library from the app and look for an alternative on iOS despite Android being approved. 


Thanks!
