### ISSUE TITLE
iOS Setup - Type 'SwiftAlarmPlugin' has no member 'registerBackgroundTasks'

### ISSUE THREAD

**Issue by victorshin12** [gdelataillade/alarm#97]
**Alarm plugin version**
2.0.0

**Describe the bug**
When following the steps of iOS Setup page, I get an error when I paste the following code into my App Delegate:

```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
}
SwiftAlarmPlugin.registerBackgroundTasks()
```

**To Reproduce**
*Steps to reproduce the behavior:*
1. Setup alarm clock app
2. Follow steps of INSTALL-IOS.md and paste the code into AppDelegate.swift

**Expected behavior**
No errors.

**Screenshots**
<img width="756" alt="Screenshot 2023-09-26 at 12 38 19 PM" src="https://github.com/gdelataillade/alarm/assets/63498090/72b5a601-7132-4b23-b2c7-ba1717b11955">
<img width="694" alt="Screenshot 2023-09-26 at 12 38 40 PM" src="https://github.com/gdelataillade/alarm/assets/63498090/f6e59066-cb9d-46fe-8ca0-3153f60ae734">
<img width="500" alt="Screenshot 2023-09-26 at 12 39 06 PM" src="https://github.com/gdelataillade/alarm/assets/63498090/33857bf9-6dde-41e6-b813-b392dee7a9ce">

**Device info**
XCode 14.3.1

**Comment by gdelataillade** [comment]
Hi @victorshin12,

That's weird, `registerBackgroundTasks` is located in the `SwiftAlarmPlugin` class.

Try to run `pod install --repo-update` in your **ios** folder.

Let me know if it fixes the issue.

**Comment by victorshin12** [comment]
Thanks for the advice.

The pod install didn't do much, but I found a workaround by copying and pasting the github file code of SwiftAlarmPlugin.swift into my project file's SwiftAlarmPlugin.swift.

Don't know what's causing the project file to not be updated when pods are installed, but might be case-by-case issue.
